import type { ResourceSchema } from '@terrastudio/types';

export const keyVaultKeySchema: ResourceSchema = {
  typeId: 'azurerm/security/key_vault_key',
  provider: 'azurerm',
  displayName: 'Key Vault Key',
  category: 'security',
  description: 'A cryptographic key stored in Azure Key Vault',
  terraformType: 'azurerm_key_vault_key',
  supportsTags: true,
  requiresResourceGroup: false,
  canBeChildOf: ['azurerm/security/key_vault'],
  parentReference: { propertyKey: 'key_vault_id' },
  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'my-key',
      group: 'General',
      order: 1,
      validation: {
        minLength: 1,
        maxLength: 127,
        pattern: '^[a-zA-Z0-9-]+$',
        patternMessage: 'Alphanumerics and hyphens only',
      },
    },
    {
      key: 'key_type',
      label: 'Key Type',
      type: 'select',
      required: true,
      group: 'General',
      order: 2,
      defaultValue: 'RSA',
      options: [
        { label: 'RSA', value: 'RSA' },
        { label: 'RSA-HSM', value: 'RSA-HSM' },
        { label: 'EC', value: 'EC' },
        { label: 'EC-HSM', value: 'EC-HSM' },
      ],
    },
    {
      key: 'key_size',
      label: 'Key Size',
      type: 'select',
      required: false,
      group: 'General',
      order: 3,
      defaultValue: '2048',
      visibleWhen: { field: 'key_type', operator: 'in', value: 'RSA,RSA-HSM' },
      options: [
        { label: '2048', value: '2048' },
        { label: '3072', value: '3072' },
        { label: '4096', value: '4096' },
      ],
    },
    {
      key: 'curve',
      label: 'Curve',
      type: 'select',
      required: false,
      group: 'General',
      order: 4,
      defaultValue: 'P-256',
      visibleWhen: { field: 'key_type', operator: 'in', value: 'EC,EC-HSM' },
      options: [
        { label: 'P-256', value: 'P-256' },
        { label: 'P-256K', value: 'P-256K' },
        { label: 'P-384', value: 'P-384' },
        { label: 'P-521', value: 'P-521' },
      ],
    },
    {
      key: 'expiration_date',
      label: 'Expiration Date',
      type: 'string',
      required: false,
      group: 'General',
      order: 5,
      placeholder: '2025-12-31T00:00:00Z',
      description: 'ISO 8601 date when the key expires',
    },
  ],
  handles: [],
  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'version', label: 'Version', terraformAttribute: 'version' },
    { key: 'versionless_id', label: 'Versionless ID', terraformAttribute: 'versionless_id' },
  ],

  costEstimation: {
    serviceName: 'Key Vault',
    staticMonthlyCost: 0,
  },
};
