import type { ResourceSchema } from '@terrastudio/types';

export const s3BucketSchema: ResourceSchema = {
  typeId: 'aws/storage/s3_bucket',
  provider: 'aws',
  displayName: 'S3 Bucket',
  category: 'aws-storage',
  description: 'AWS S3 object storage bucket',
  terraformType: 'aws_s3_bucket',
  supportsTags: true,
  requiresResourceGroup: false,

  properties: [
    {
      key: 'name',
      label: 'Bucket Name',
      type: 'string',
      required: true,
      placeholder: 'my-app-bucket',
      group: 'General',
      order: 1,
      validation: {
        minLength: 3,
        maxLength: 63,
        pattern: '^[a-z0-9][a-z0-9.-]*[a-z0-9]$',
        patternMessage: 'Lowercase letters, numbers, hyphens, and dots. Must start and end with letter or number.',
      },
    },
    {
      key: 'force_destroy',
      label: 'Force Destroy',
      type: 'boolean',
      required: false,
      defaultValue: false,
      group: 'General',
      order: 2,
      description: 'Allow Terraform to destroy the bucket even if it contains objects',
    },
    {
      key: 'versioning_enabled',
      label: 'Versioning',
      type: 'boolean',
      required: false,
      defaultValue: false,
      group: 'Settings',
      order: 3,
      description: 'Enable object versioning',
    },
    {
      key: 'acl',
      label: 'ACL',
      type: 'select',
      required: false,
      defaultValue: 'private',
      group: 'Settings',
      order: 4,
      options: [
        { label: 'Private', value: 'private' },
        { label: 'Public Read', value: 'public-read' },
        { label: 'Public Read/Write', value: 'public-read-write' },
        { label: 'Authenticated Read', value: 'authenticated-read' },
      ],
    },
    {
      key: 'encryption',
      label: 'Encryption',
      type: 'select',
      required: false,
      defaultValue: 'AES256',
      group: 'Security',
      order: 5,
      options: [
        { label: 'SSE-S3 (AES256)', value: 'AES256' },
        { label: 'SSE-KMS', value: 'aws:kms' },
      ],
    },
    {
      key: 'lifecycle_rules',
      label: 'Lifecycle Rules',
      type: 'array',
      required: false,
      group: 'Lifecycle',
      order: 6,
      itemSchema: {
        key: 'lifecycle_rule',
        label: 'Lifecycle Rule',
        type: 'object',
        required: false,
        nestedSchema: [
          {
            key: 'id',
            label: 'Rule ID',
            type: 'string',
            required: true,
          },
          {
            key: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            defaultValue: 'Enabled',
            options: [
              { label: 'Enabled', value: 'Enabled' },
              { label: 'Disabled', value: 'Disabled' },
            ],
          },
          {
            key: 'prefix',
            label: 'Prefix Filter',
            type: 'string',
            required: false,
            placeholder: 'logs/',
          },
          {
            key: 'transition_days',
            label: 'Transition After (days)',
            type: 'number',
            required: false,
            validation: { min: 0 },
            description: 'Move to cheaper storage class after N days',
          },
          {
            key: 'transition_storage_class',
            label: 'Target Storage Class',
            type: 'select',
            required: false,
            options: [
              { label: 'Standard-IA', value: 'STANDARD_IA' },
              { label: 'One Zone-IA', value: 'ONEZONE_IA' },
              { label: 'Intelligent-Tiering', value: 'INTELLIGENT_TIERING' },
              { label: 'Glacier', value: 'GLACIER' },
              { label: 'Glacier Instant Retrieval', value: 'GLACIER_IR' },
              { label: 'Deep Archive', value: 'DEEP_ARCHIVE' },
            ],
          },
          {
            key: 'expiration_days',
            label: 'Delete After (days)',
            type: 'number',
            required: false,
            validation: { min: 0 },
            description: 'Permanently delete objects after N days',
          },
        ],
      },
    },
    {
      key: 'cors_enabled',
      label: 'Enable CORS',
      type: 'boolean',
      required: false,
      defaultValue: false,
      group: 'CORS',
      order: 7,
    },
    {
      key: 'cors_allowed_origins',
      label: 'Allowed Origins',
      type: 'array',
      required: false,
      group: 'CORS',
      order: 8,
      visibleWhen: { field: 'cors_enabled', operator: 'truthy' },
      itemSchema: {
        key: 'origin',
        label: 'Origin',
        type: 'string',
        required: true,
      },
    },
    {
      key: 'cors_allowed_methods',
      label: 'Allowed Methods',
      type: 'multiselect',
      required: false,
      group: 'CORS',
      order: 9,
      visibleWhen: { field: 'cors_enabled', operator: 'truthy' },
      options: [
        { label: 'GET', value: 'GET' },
        { label: 'PUT', value: 'PUT' },
        { label: 'POST', value: 'POST' },
        { label: 'DELETE', value: 'DELETE' },
        { label: 'HEAD', value: 'HEAD' },
      ],
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'Bucket ID', terraformAttribute: 'id' },
    { key: 'arn', label: 'ARN', terraformAttribute: 'arn' },
    { key: 'bucket_domain_name', label: 'Domain Name', terraformAttribute: 'bucket_domain_name' },
    { key: 'bucket_regional_domain_name', label: 'Regional Domain', terraformAttribute: 'bucket_regional_domain_name' },
  ],

  costEstimation: {
    serviceName: 'S3',
    usageInputs: [
      {
        key: '_cost_storage_gb',
        label: 'Estimated Storage',
        unit: 'GB',
        defaultValue: 100,
        min: 0,
        max: 1000000,
        description: 'Total data stored in the bucket (~$0.023/GB for Standard)',
      },
    ],
  },
};
