import type { ResourceSchema } from '@terrastudio/types';

export const cosmosdbAccountSchema: ResourceSchema = {
  typeId: 'azurerm/database/cosmosdb_account',
  provider: 'azurerm',
  displayName: 'Cosmos DB Account',
  category: 'cosmosdb',
  description: 'Azure Cosmos DB account — globally distributed, multi-model NoSQL database',
  terraformType: 'azurerm_cosmosdb_account',
  supportsTags: true,
  requiresResourceGroup: true,
  cafAbbreviation: 'cosmos',
  namingConstraints: { lowercase: true, maxLength: 44 },
  isContainer: true,

  canBeChildOf: [
    'azurerm/core/resource_group',
  ],

  containerStyle: {
    borderColor: '#2B7CF6',
    borderStyle: 'dotted',
    backgroundColor: '#ffffff',
    headerColor: '#1a1a2e',
    borderRadius: 12,
    borderWidth: 3,
    hideHeaderBorder: true,
    iconSize: 28,
    labelSize: 16,
    dashArray: '4,8',
  },

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'cosmos-myapp-dev',
      group: 'General',
      order: 1,
      validation: {
        minLength: 3,
        maxLength: 44,
        pattern: '^[a-z0-9][a-z0-9-]*[a-z0-9]$',
        patternMessage: 'Lowercase letters, numbers, and hyphens only; globally unique',
      },
    },
    {
      key: 'kind',
      label: 'API Kind',
      type: 'select',
      required: true,
      group: 'General',
      order: 2,
      defaultValue: 'GlobalDocumentDB',
      options: [
        { label: 'NoSQL (Core SQL)', value: 'GlobalDocumentDB' },
        { label: 'MongoDB', value: 'MongoDB' },
      ],
    },
    {
      key: 'consistency_level',
      label: 'Consistency Level',
      type: 'select',
      required: true,
      group: 'General',
      order: 3,
      defaultValue: 'Session',
      options: [
        { label: 'Eventual (lowest latency)', value: 'Eventual' },
        { label: 'Consistent Prefix', value: 'ConsistentPrefix' },
        { label: 'Session (recommended)', value: 'Session' },
        { label: 'Bounded Staleness', value: 'BoundedStaleness' },
        { label: 'Strong (highest consistency)', value: 'Strong' },
      ],
    },
    {
      key: 'geo_redundant_backup_enabled',
      label: 'Geo-Redundant Backup',
      type: 'boolean',
      required: false,
      group: 'Availability',
      order: 4,
      defaultValue: false,
    },
    {
      key: 'multiple_write_locations_enabled',
      label: 'Multi-Region Writes',
      type: 'boolean',
      required: false,
      group: 'Availability',
      order: 5,
      defaultValue: false,
      description: 'Enable writes in multiple Azure regions simultaneously',
    },
    {
      key: 'automatic_failover_enabled',
      label: 'Automatic Failover',
      type: 'boolean',
      required: false,
      group: 'Availability',
      order: 6,
      defaultValue: true,
    },
    {
      key: 'public_network_access_enabled',
      label: 'Public Network Access',
      type: 'boolean',
      required: false,
      group: 'Security',
      order: 7,
      defaultValue: true,
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'endpoint', label: 'Endpoint URL', terraformAttribute: 'endpoint' },
    { key: 'primary_key', label: 'Primary Key', terraformAttribute: 'primary_key', sensitive: true },
    { key: 'primary_connection_string', label: 'Primary Connection String', terraformAttribute: 'primary_connection_string', sensitive: true },
  ],

  costEstimation: {
    serviceName: 'Azure Cosmos DB',
    usageInputs: [
      {
        key: '_cost_rus',
        label: 'Provisioned Throughput',
        unit: 'RU/s',
        defaultValue: 400,
        min: 100,
        max: 1000000,
        description: 'Provisioned request units per second (~$0.008/RU/hr for manual throughput)',
      },
      {
        key: '_cost_storage_gb',
        label: 'Data Storage',
        unit: 'GB',
        defaultValue: 10,
        min: 0,
        max: 1000000,
        description: 'Total data stored (~$0.25/GB/month)',
      },
    ],
  },
};
