import type { ResourceSchema } from '@terrastudio/types';

export const vmSchema: ResourceSchema = {
  typeId: 'azurerm/compute/virtual_machine',
  provider: 'azurerm',
  displayName: 'Virtual Machine',
  category: 'compute',
  description: 'Azure Virtual Machine (Linux or Windows)',
  terraformType: 'azurerm_linux_virtual_machine',
  supportsTags: true,
  requiresResourceGroup: true,
  canBeChildOf: [
    'azurerm/networking/subnet',
  ],

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'vm-web-01',
      group: 'General',
      order: 1,
      validation: {
        minLength: 1,
        maxLength: 64,
        pattern: '^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]$',
        patternMessage: 'Alphanumerics and hyphens, must start and end with alphanumeric',
      },
    },
    {
      key: 'os_type',
      label: 'OS Type',
      type: 'select',
      required: true,
      group: 'General',
      order: 2,
      defaultValue: 'linux',
      options: [
        { label: 'Linux', value: 'linux' },
        { label: 'Windows', value: 'windows' },
      ],
    },
    {
      key: 'size',
      label: 'VM Size',
      type: 'select',
      required: true,
      group: 'General',
      order: 3,
      defaultValue: 'Standard_B2s',
      options: [
        { label: 'B1s (1 vCPU, 1 GB)', value: 'Standard_B1s' },
        { label: 'B2s (2 vCPU, 4 GB)', value: 'Standard_B2s' },
        { label: 'B2ms (2 vCPU, 8 GB)', value: 'Standard_B2ms' },
        { label: 'D2s v3 (2 vCPU, 8 GB)', value: 'Standard_D2s_v3' },
        { label: 'D4s v3 (4 vCPU, 16 GB)', value: 'Standard_D4s_v3' },
        { label: 'D8s v3 (8 vCPU, 32 GB)', value: 'Standard_D8s_v3' },
      ],
    },
    {
      key: 'admin_username',
      label: 'Admin Username',
      type: 'string',
      required: true,
      group: 'Authentication',
      order: 4,
      defaultValue: 'azureuser',
      placeholder: 'azureuser',
    },
    {
      key: 'admin_password',
      label: 'Admin Password',
      type: 'string',
      required: false,
      group: 'Authentication',
      order: 5,
      description: 'Required for Windows VMs. Will be stored as a sensitive Terraform variable.',
      visibleWhen: { field: 'os_type', operator: 'eq', value: 'windows' },
    },
    {
      key: 'image_publisher',
      label: 'Image Publisher',
      type: 'string',
      required: true,
      group: 'OS Image',
      order: 5,
      defaultValue: 'Canonical',
      placeholder: 'Canonical',
    },
    {
      key: 'image_offer',
      label: 'Image Offer',
      type: 'string',
      required: true,
      group: 'OS Image',
      order: 6,
      defaultValue: '0001-com-ubuntu-server-jammy',
      placeholder: '0001-com-ubuntu-server-jammy',
    },
    {
      key: 'image_sku',
      label: 'Image SKU',
      type: 'string',
      required: true,
      group: 'OS Image',
      order: 7,
      defaultValue: '22_04-lts',
      placeholder: '22_04-lts',
    },
    {
      key: 'os_disk_size_gb',
      label: 'OS Disk Size (GB)',
      type: 'number',
      required: false,
      group: 'Storage',
      order: 8,
      defaultValue: 30,
    },
    {
      key: 'os_disk_type',
      label: 'OS Disk Type',
      type: 'select',
      required: true,
      group: 'Storage',
      order: 9,
      defaultValue: 'Standard_LRS',
      options: [
        { label: 'Standard HDD', value: 'Standard_LRS' },
        { label: 'Standard SSD', value: 'StandardSSD_LRS' },
        { label: 'Premium SSD', value: 'Premium_LRS' },
      ],
    },
    {
      key: 'public_ip_enabled',
      label: 'Public IP Address',
      type: 'boolean',
      required: false,
      group: 'Networking',
      order: 10,
      defaultValue: false,
      description: 'Associate a Public IP address with this VM NIC',
    },
    {
      key: 'public_ip_id',
      label: 'Public IP',
      type: 'reference',
      required: false,
      group: 'Networking',
      order: 11,
      referenceTargetTypes: ['azurerm/networking/public_ip'],
      visibleWhen: { field: 'public_ip_enabled', operator: 'truthy' },
    },
    {
      key: 'nsg_enabled',
      label: 'Network Security Group',
      type: 'boolean',
      required: false,
      group: 'Security',
      order: 12,
      defaultValue: false,
      description: 'Associate a Network Security Group with this VM NIC',
    },
    {
      key: 'nsg_id',
      label: 'NSG',
      type: 'reference',
      required: false,
      group: 'Security',
      order: 13,
      referenceTargetTypes: ['azurerm/networking/network_security_group'],
      visibleWhen: { field: 'nsg_enabled', operator: 'truthy' },
    },
  ],

  parentReference: { propertyKey: 'subnet_id' },

  handles: [],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'private_ip_address', label: 'Private IP', terraformAttribute: 'private_ip_address' },
    { key: 'public_ip_address', label: 'Public IP', terraformAttribute: 'public_ip_address' },
  ],
};
