import type { ResourceSchema } from '@terrastudio/types';

export const redisCacheSchema: ResourceSchema = {
  typeId: 'azurerm/database/redis_cache',
  provider: 'azurerm',
  displayName: 'Redis Cache',
  category: 'cache',
  description: 'Azure Cache for Redis — in-memory data store for session management, caching, and pub/sub',
  terraformType: 'azurerm_redis_cache',
  supportsTags: true,
  requiresResourceGroup: true,
  cafAbbreviation: 'redis',
  namingConstraints: { maxLength: 63 },

  canBeChildOf: [
    'azurerm/core/resource_group',
  ],

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'redis-myapp-dev',
      group: 'General',
      order: 1,
      validation: {
        minLength: 1,
        maxLength: 63,
        pattern: '^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]$',
        patternMessage: 'Alphanumerics and hyphens, must start and end with alphanumeric',
      },
    },
    {
      key: 'sku_name',
      label: 'SKU',
      type: 'select',
      required: true,
      group: 'General',
      order: 2,
      defaultValue: 'Standard',
      options: [
        { label: 'Basic (no SLA, single node)', value: 'Basic' },
        { label: 'Standard (replicated, SLA)', value: 'Standard' },
        { label: 'Premium (geo-replication, VNet, cluster)', value: 'Premium' },
      ],
    },
    {
      key: 'family',
      label: 'Family',
      type: 'select',
      required: true,
      group: 'General',
      order: 3,
      defaultValue: 'C',
      options: [
        { label: 'C (Basic/Standard)', value: 'C' },
        { label: 'P (Premium)', value: 'P' },
      ],
      description: 'Must match SKU: C for Basic/Standard, P for Premium',
    },
    {
      key: 'capacity',
      label: 'Capacity',
      type: 'select',
      required: true,
      group: 'General',
      order: 4,
      defaultValue: '1',
      options: [
        { label: '0 (250 MB)', value: '0' },
        { label: '1 (1 GB)', value: '1' },
        { label: '2 (2.5 GB)', value: '2' },
        { label: '3 (6 GB)', value: '3' },
        { label: '4 (13 GB)', value: '4' },
        { label: '5 (26 GB)', value: '5' },
        { label: '6 (53 GB)', value: '6' },
      ],
    },
    {
      key: 'redis_version',
      label: 'Redis Version',
      type: 'select',
      required: false,
      group: 'General',
      order: 5,
      defaultValue: '6',
      options: [
        { label: '6 (recommended)', value: '6' },
        { label: '4 (legacy)', value: '4' },
      ],
    },
    {
      key: 'minimum_tls_version',
      label: 'Minimum TLS Version',
      type: 'select',
      required: false,
      group: 'Security',
      order: 6,
      defaultValue: '1.2',
      options: [
        { label: 'TLS 1.2 (recommended)', value: '1.2' },
        { label: 'TLS 1.1', value: '1.1' },
        { label: 'TLS 1.0', value: '1.0' },
      ],
    },
    {
      key: 'enable_non_ssl_port',
      label: 'Enable Non-SSL Port (6379)',
      type: 'boolean',
      required: false,
      group: 'Security',
      order: 7,
      defaultValue: false,
      description: 'Enable the non-SSL Redis port (not recommended for production)',
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'hostname', label: 'Hostname', terraformAttribute: 'hostname' },
    { key: 'ssl_port', label: 'SSL Port', terraformAttribute: 'ssl_port' },
    { key: 'primary_access_key', label: 'Primary Access Key', terraformAttribute: 'primary_access_key', sensitive: true },
    { key: 'primary_connection_string', label: 'Primary Connection String', terraformAttribute: 'primary_connection_string', sensitive: true },
  ],
};
