import type { ResourceSchema } from '@terrastudio/types';

export const mssqlServerSchema: ResourceSchema = {
  typeId: 'azurerm/database/mssql_server',
  provider: 'azurerm',
  displayName: 'SQL Server',
  category: 'database',
  description: 'Azure SQL Server for hosting SQL databases',
  terraformType: 'azurerm_mssql_server',
  supportsTags: true,
  requiresResourceGroup: true,
  cafAbbreviation: 'sql',
  namingConstraints: { lowercase: true, maxLength: 63 },
  isContainer: true,

  canBeChildOf: [
    'azurerm/core/resource_group',
    'azurerm/networking/subnet',
  ],
  visualContainment: true,
  privateEndpointConfig: {
    subresources: [
      { key: 'sqlServer', label: 'SQL Server' },
    ],
    defaultSubresource: 'sqlServer',
  },

  containerStyle: {
    borderColor: '#2B7CF6',
    borderStyle: 'dotted',
    backgroundColor: '#ffffff',
    headerColor: '#1a1a2e',
    borderRadius: 12,
    borderWidth: 3,
    hideHeaderBorder: true,
    iconSize: 28,
    labelSize: 16,
    dashArray: '4,8',
  },

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'sql-myapp-dev',
      group: 'General',
      order: 1,
      description: 'Globally unique server name',
      validation: {
        minLength: 1,
        maxLength: 63,
        pattern: '^[a-z0-9][a-z0-9-]*[a-z0-9]$',
        patternMessage: 'Lowercase alphanumeric and hyphens only, must start and end with alphanumeric',
      },
    },
    {
      key: 'version',
      label: 'Server Version',
      type: 'select',
      required: true,
      group: 'General',
      order: 2,
      defaultValue: '12.0',
      options: [
        { label: '12.0', value: '12.0' },
      ],
    },
    {
      key: 'administrator_login',
      label: 'Admin Login',
      type: 'string',
      required: true,
      group: 'Authentication',
      order: 3,
      placeholder: 'sqladmin',
      validation: {
        minLength: 1,
        maxLength: 128,
        pattern: '^[a-zA-Z][a-zA-Z0-9_]*$',
        patternMessage: 'Must start with a letter, followed by letters, digits, or underscores',
      },
    },
    {
      key: 'administrator_login_password',
      label: 'Admin Password',
      type: 'string',
      required: true,
      sensitive: true,
      group: 'Authentication',
      order: 4,
      description: 'Will be stored as a sensitive Terraform variable',
      validation: {
        minLength: 8,
        maxLength: 128,
      },
    },
    {
      key: 'minimum_tls_version',
      label: 'Minimum TLS',
      type: 'select',
      required: false,
      group: 'Security',
      order: 5,
      defaultValue: '1.2',
      options: [
        { label: 'TLS 1.0', value: '1.0' },
        { label: 'TLS 1.1', value: '1.1' },
        { label: 'TLS 1.2', value: '1.2' },
      ],
    },
    {
      key: 'public_network_access_enabled',
      label: 'Public Network Access',
      type: 'boolean',
      required: false,
      group: 'Security',
      order: 6,
      defaultValue: true,
    },
    {
      key: 'connection_policy',
      label: 'Connection Policy',
      type: 'select',
      required: false,
      group: 'Networking',
      order: 7,
      defaultValue: 'Default',
      options: [
        { label: 'Default', value: 'Default' },
        { label: 'Proxy', value: 'Proxy' },
        { label: 'Redirect', value: 'Redirect' },
      ],
    },
    {
      key: 'outbound_network_restriction_enabled',
      label: 'Outbound Network Restriction',
      type: 'boolean',
      required: false,
      group: 'Networking',
      order: 8,
      defaultValue: false,
    },
    {
      key: 'identity_enabled',
      label: 'Enable Managed Identity',
      type: 'boolean',
      required: false,
      group: 'Identity',
      order: 9,
      defaultValue: false,
    },
    {
      key: 'identity_type',
      label: 'Identity Type',
      type: 'select',
      required: false,
      group: 'Identity',
      order: 10,
      defaultValue: 'SystemAssigned',
      visibleWhen: { field: 'identity_enabled', operator: 'truthy' },
      options: [
        { label: 'System Assigned', value: 'SystemAssigned' },
        { label: 'User Assigned', value: 'UserAssigned' },
        { label: 'System & User Assigned', value: 'SystemAssigned, UserAssigned' },
      ],
    },
    {
      key: 'azuread_auth_only',
      label: 'Azure AD Only Authentication',
      type: 'boolean',
      required: false,
      group: 'Authentication',
      order: 11,
      defaultValue: false,
      description: 'When true, only Azure AD authentication is allowed',
    },
    {
      key: 'azuread_admin_login',
      label: 'Azure AD Admin Login',
      type: 'string',
      required: false,
      group: 'Authentication',
      order: 12,
      placeholder: 'admin@example.com',
    },
    {
      key: 'azuread_admin_object_id',
      label: 'Azure AD Admin Object ID',
      type: 'string',
      required: false,
      group: 'Authentication',
      order: 13,
      placeholder: '00000000-0000-0000-0000-000000000000',
    },
  ],

  handles: [
    {
      id: 'pep-target',
      type: 'target',
      position: 'left',
      label: 'Private Endpoint',
    },
  ],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'fully_qualified_domain_name', label: 'FQDN', terraformAttribute: 'fully_qualified_domain_name' },
  ],

  costEstimation: {
    serviceName: 'SQL Database',
    staticMonthlyCost: 0,
  },
};
