import type { ResourceSchema } from '@terrastudio/types';

export const subnetSchema: ResourceSchema = {
  typeId: 'aws/networking/subnet',
  provider: 'aws',
  displayName: 'Subnet',
  category: 'aws-networking',
  description: 'AWS Subnet within a VPC',
  terraformType: 'aws_subnet',
  supportsTags: true,
  requiresResourceGroup: false,
  isContainer: true,
  canBeChildOf: [
    'aws/networking/vpc',
  ],
  parentReference: { propertyKey: 'vpc_id' },
  containerStyle: {
    borderColor: '#c0c0c0',
    borderStyle: 'solid',
    backgroundColor: '#f5f5f5',
    headerColor: '#1a1a2e',
    borderRadius: 0,
    borderWidth: 1.5,
    hideHeaderBorder: true,
    iconSize: 0,
    labelSize: 16,
  },
  minSize: { width: 200, height: 150 },

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'my-subnet',
      group: 'General',
      order: 1,
      validation: {
        minLength: 1,
        maxLength: 255,
      },
    },
    {
      key: 'cidr_block',
      label: 'CIDR Block',
      type: 'cidr',
      required: true,
      description: 'IPv4 CIDR block for the subnet',
      group: 'Networking',
      order: 2,
      defaultValue: '10.0.1.0/24',
    },
    {
      key: 'availability_zone',
      label: 'Availability Zone',
      type: 'select',
      required: false,
      description: 'Availability zone for the subnet',
      group: 'Networking',
      order: 3,
      defaultValue: 'us-east-1a',
      options: [
        { label: 'us-east-1a', value: 'us-east-1a' },
        { label: 'us-east-1b', value: 'us-east-1b' },
        { label: 'us-east-1c', value: 'us-east-1c' },
        { label: 'us-east-1d', value: 'us-east-1d' },
        { label: 'us-east-1e', value: 'us-east-1e' },
        { label: 'us-east-1f', value: 'us-east-1f' },
      ],
    },
    {
      key: 'map_public_ip_on_launch',
      label: 'Auto-assign Public IP',
      type: 'boolean',
      required: false,
      group: 'Networking',
      order: 4,
      defaultValue: false,
      description: 'Automatically assign a public IP to instances launched in this subnet',
    },
    {
      key: 'route_table_enabled',
      label: 'Route Table',
      type: 'boolean',
      required: false,
      group: 'Routing',
      order: 20,
      defaultValue: false,
      description: 'Associate a Route Table with this subnet',
    },
    {
      key: 'route_table_id',
      label: 'Route Table',
      type: 'reference',
      required: false,
      group: 'Routing',
      order: 21,
      referenceTargetTypes: ['aws/networking/route_table'],
      visibleWhen: { field: 'route_table_enabled', operator: 'truthy' },
    },
  ],

  handles: [
    {
      id: 'subnet-out',
      type: 'source',
      position: 'right',
      label: 'Subnet',
    },
  ],

  outputs: [
    { key: 'id', label: 'Subnet ID', terraformAttribute: 'id' },
    { key: 'arn', label: 'ARN', terraformAttribute: 'arn' },
    { key: 'availability_zone', label: 'Availability Zone', terraformAttribute: 'availability_zone' },
  ],

  costEstimation: { serviceName: 'Amazon VPC', staticMonthlyCost: 0 },
};
