import type { ResourceSchema } from '@terrastudio/types';

export const firewallSchema: ResourceSchema = {
  typeId: 'azurerm/networking/firewall',
  provider: 'azurerm',
  displayName: 'Azure Firewall',
  category: 'networking',
  description: 'Azure Firewall — managed, cloud-based network security service that protects Azure Virtual Network resources',
  terraformType: 'azurerm_firewall',
  supportsTags: true,
  requiresResourceGroup: true,
  cafAbbreviation: 'afw',
  namingConstraints: { maxLength: 80 },

  canBeChildOf: [
    'azurerm/core/resource_group',
  ],

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'afw-myapp-dev',
      group: 'General',
      order: 1,
      validation: {
        minLength: 1,
        maxLength: 80,
        pattern: '^[a-zA-Z0-9][a-zA-Z0-9_.-]*[a-zA-Z0-9_]$',
        patternMessage: 'Must start with alphanumeric, end with alphanumeric or underscore',
      },
    },
    {
      key: 'sku_name',
      label: 'SKU Name',
      type: 'select',
      required: true,
      group: 'General',
      order: 2,
      defaultValue: 'AZFW_VNet',
      options: [
        { label: 'VNet (AZFW_VNet)', value: 'AZFW_VNet' },
        { label: 'Hub (AZFW_Hub)', value: 'AZFW_Hub' },
      ],
    },
    {
      key: 'sku_tier',
      label: 'SKU Tier',
      type: 'select',
      required: true,
      group: 'General',
      order: 3,
      defaultValue: 'Standard',
      options: [
        { label: 'Basic', value: 'Basic' },
        { label: 'Standard', value: 'Standard' },
        { label: 'Premium', value: 'Premium' },
      ],
    },
    {
      key: 'threat_intel_mode',
      label: 'Threat Intelligence Mode',
      type: 'select',
      required: false,
      group: 'Security',
      order: 10,
      defaultValue: 'Alert',
      options: [
        { label: 'Off', value: 'Off' },
        { label: 'Alert', value: 'Alert' },
        { label: 'Deny', value: 'Deny' },
      ],
      description: 'Threat intelligence-based filtering mode',
    },
    {
      key: 'dns_proxy_enabled',
      label: 'DNS Proxy',
      type: 'boolean',
      required: false,
      group: 'DNS',
      order: 20,
      defaultValue: false,
      description: 'Enable DNS proxy to forward DNS queries through the firewall',
    },
    {
      key: 'dns_servers',
      label: 'DNS Servers',
      type: 'array',
      required: false,
      group: 'DNS',
      order: 21,
      description: 'Custom DNS servers (IP addresses)',
    },
    {
      key: 'zones',
      label: 'Availability Zones',
      type: 'array',
      required: false,
      group: 'Availability',
      order: 30,
      description: 'Availability zones (e.g., 1, 2, 3)',
    },
    {
      key: 'firewall_policy_id',
      label: 'Firewall Policy ID',
      type: 'string',
      required: false,
      group: 'Policy',
      order: 40,
      placeholder: '/subscriptions/.../firewallPolicies/...',
      description: 'ID of an existing Azure Firewall Policy to associate',
    },
    {
      key: 'subnet_id',
      label: 'Subnet',
      type: 'reference',
      required: false,
      group: 'Network',
      order: 50,
      referenceTargetTypes: ['azurerm/networking/subnet'],
      description: 'The subnet must be named "AzureFirewallSubnet" with at least /26 CIDR',
    },
    {
      key: 'pip_id',
      label: 'Public IP',
      type: 'reference',
      required: false,
      group: 'Network',
      order: 51,
      referenceTargetTypes: ['azurerm/networking/public_ip'],
      description: 'Standard SKU Public IP address (Static allocation required)',
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'private_ip_address', label: 'Private IP', terraformAttribute: 'ip_configuration.0.private_ip_address' },
    { key: 'public_ip_address', label: 'Public IP', terraformAttribute: 'ip_configuration.0.public_ip_address_id' },
  ],

  costEstimation: {
    serviceName: 'Azure Firewall',
    skuProperty: 'sku_tier',
    usageInputs: [
      {
        key: '_cost_data_processed_gb',
        label: 'Data Processed',
        unit: 'GB/mo',
        defaultValue: 100,
        min: 0,
        max: 1000000,
        description: 'Data processed through the firewall per month',
      },
    ],
  },
};
