import type { ResourceSchema } from '@terrastudio/types';

export const eksNodeGroupSchema: ResourceSchema = {
  typeId: 'aws/containers/eks_node_group',
  provider: 'aws',
  displayName: 'EKS Node Group',
  category: 'aws-containers',
  description: 'Managed node group for Amazon EKS — auto-provisioned EC2 worker nodes',
  terraformType: 'aws_eks_node_group',
  supportsTags: true,
  requiresResourceGroup: false,
  canBeChildOf: ['aws/containers/eks_cluster'],
  parentReference: { propertyKey: 'cluster_name' },

  properties: [
    {
      key: 'name',
      label: 'Node Group Name',
      type: 'string',
      required: true,
      placeholder: 'default-nodes',
      group: 'General',
      order: 1,
    },
    {
      key: 'instance_types',
      label: 'Instance Types',
      type: 'select',
      required: true,
      defaultValue: 't3.medium',
      options: [
        { label: 't3.small', value: 't3.small' },
        { label: 't3.medium', value: 't3.medium' },
        { label: 't3.large', value: 't3.large' },
        { label: 't3.xlarge', value: 't3.xlarge' },
        { label: 'm5.large', value: 'm5.large' },
        { label: 'm5.xlarge', value: 'm5.xlarge' },
        { label: 'c5.large', value: 'c5.large' },
        { label: 'c5.xlarge', value: 'c5.xlarge' },
        { label: 'r5.large', value: 'r5.large' },
        { label: 'r5.xlarge', value: 'r5.xlarge' },
      ],
      group: 'General',
      order: 2,
    },
    {
      key: 'desired_size',
      label: 'Desired Size',
      type: 'number',
      required: true,
      defaultValue: 2,
      group: 'Scaling',
      order: 3,
      validation: { min: 0, max: 100 },
    },
    {
      key: 'min_size',
      label: 'Minimum Size',
      type: 'number',
      required: true,
      defaultValue: 1,
      group: 'Scaling',
      order: 4,
      validation: { min: 0, max: 100 },
    },
    {
      key: 'max_size',
      label: 'Maximum Size',
      type: 'number',
      required: true,
      defaultValue: 3,
      group: 'Scaling',
      order: 5,
      validation: { min: 1, max: 100 },
    },
    {
      key: 'disk_size',
      label: 'Disk Size (GB)',
      type: 'number',
      required: false,
      defaultValue: 20,
      group: 'Storage',
      order: 6,
      validation: { min: 1, max: 16384 },
    },
    {
      key: 'capacity_type',
      label: 'Capacity Type',
      type: 'select',
      required: false,
      defaultValue: 'ON_DEMAND',
      options: [
        { label: 'On-Demand', value: 'ON_DEMAND' },
        { label: 'Spot', value: 'SPOT' },
      ],
      group: 'General',
      order: 7,
      description: 'Spot instances can reduce costs by up to 90%',
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'Node Group ID', terraformAttribute: 'id' },
    { key: 'arn', label: 'ARN', terraformAttribute: 'arn' },
    { key: 'status', label: 'Status', terraformAttribute: 'status' },
  ],

  costEstimation: {
    serviceName: 'EKS Node Group',
    skuProperty: 'instance_types',
  },
};
