import type { ResourceSchema } from '@terrastudio/types';

export const aiFoundrySchema: ResourceSchema = {
  typeId: 'azurerm/ai/ai_foundry',
  provider: 'azurerm',
  displayName: 'AI Foundry Hub',
  category: 'ai',
  description: 'Azure AI Foundry hub for managing AI projects, models, and deployments',
  terraformType: 'azurerm_ai_foundry',
  supportsTags: true,
  requiresResourceGroup: true,
  cafAbbreviation: 'aif',
  isContainer: true,

  canBeChildOf: [
    'azurerm/core/resource_group',
  ],

  containerStyle: {
    borderColor: '#7B2FE6',
    borderStyle: 'dashed',
    backgroundColor: '#ffffff',
    headerColor: '#1a1a2e',
    borderRadius: 16,
    borderWidth: 3,
    hideHeaderBorder: true,
    iconSize: 28,
    labelSize: 16,
    dashArray: '12,8',
  },
  minSize: { width: 400, height: 280 },

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'aif-myproject-dev',
      group: 'General',
      order: 1,
      validation: {
        minLength: 2,
        maxLength: 64,
      },
    },
    {
      key: 'friendly_name',
      label: 'Friendly Name',
      type: 'string',
      required: false,
      placeholder: 'My AI Hub',
      group: 'General',
      order: 2,
    },
    {
      key: 'description',
      label: 'Description',
      type: 'string',
      required: false,
      placeholder: 'AI Foundry hub for team projects',
      group: 'General',
      order: 3,
    },
    {
      key: 'public_network_access',
      label: 'Public Network Access',
      type: 'select',
      required: false,
      group: 'Networking',
      order: 4,
      defaultValue: 'Enabled',
      options: [
        { label: 'Enabled', value: 'Enabled' },
        { label: 'Disabled', value: 'Disabled' },
      ],
    },
    {
      key: 'key_vault_id',
      label: 'Key Vault',
      type: 'reference',
      required: true,
      group: 'Dependencies',
      order: 5,
      referenceTargetTypes: ['azurerm/security/key_vault'],
      showAsEdge: true,
      description: 'Key Vault for secrets management',
    },
    {
      key: 'storage_account_id',
      label: 'Storage Account',
      type: 'reference',
      required: true,
      group: 'Dependencies',
      order: 6,
      referenceTargetTypes: ['azurerm/storage/storage_account'],
      showAsEdge: true,
      description: 'Storage account for data',
    },
    {
      key: 'application_insights_id',
      label: 'Application Insights',
      type: 'reference',
      required: false,
      group: 'Dependencies',
      order: 7,
      referenceTargetTypes: ['azurerm/monitoring/application_insights'],
      showAsEdge: true,
      description: 'Application Insights for monitoring',
    },
    {
      key: 'container_registry_id',
      label: 'Container Registry',
      type: 'reference',
      required: false,
      group: 'Dependencies',
      order: 8,
      referenceTargetTypes: ['azurerm/containers/container_registry'],
      showAsEdge: true,
      description: 'Container Registry for model containers',
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'discovery_url', label: 'Discovery URL', terraformAttribute: 'discovery_url' },
  ],
};
