import type { ResourceSchema } from '@terrastudio/types';

export const subnetSchema: ResourceSchema = {
  typeId: 'azurerm/networking/subnet',
  provider: 'azurerm',
  displayName: 'Subnet',
  category: 'networking',
  description: 'Azure Subnet within a Virtual Network',
  terraformType: 'azurerm_subnet',
  supportsTags: false,
  requiresResourceGroup: true,
  cafAbbreviation: 'snet',
  namingConstraints: { maxLength: 80 },
  isContainer: true,
  canBeChildOf: [
    'azurerm/networking/virtual_network',
  ],
  containerStyle: {
    borderColor: '#c0c0c0',
    borderStyle: 'solid',
    backgroundColor: '#f5f5f5',
    headerColor: '#1a1a2e',
    borderRadius: 10,
    borderWidth: 1.5,
    hideHeaderBorder: true,
    iconSize: 0,
    labelSize: 16,
  },
  minSize: { width: 200, height: 150 },

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'default',
      group: 'General',
      order: 1,
      validation: {
        minLength: 1,
        maxLength: 80,
        pattern: '^[a-zA-Z0-9][a-zA-Z0-9_.-]*[a-zA-Z0-9_]$',
        patternMessage: 'Must start with alphanumeric, end with alphanumeric or underscore',
      },
    },
    {
      key: 'address_prefixes',
      label: 'Address Prefixes',
      type: 'array',
      required: true,
      description: 'CIDR blocks for the subnet',
      group: 'Networking',
      order: 2,
      itemSchema: {
        key: 'cidr',
        label: 'CIDR Block',
        type: 'cidr',
        required: true,
        placeholder: '10.0.1.0/24',
      },
      defaultValue: ['10.0.1.0/24'],
    },
    {
      key: 'service_endpoints',
      label: 'Service Endpoints',
      type: 'multiselect',
      required: false,
      description: 'Azure service endpoints to enable',
      group: 'Advanced',
      order: 3,
      options: [
        { label: 'Microsoft.Storage', value: 'Microsoft.Storage' },
        { label: 'Microsoft.Sql', value: 'Microsoft.Sql' },
        { label: 'Microsoft.KeyVault', value: 'Microsoft.KeyVault' },
        { label: 'Microsoft.Web', value: 'Microsoft.Web' },
      ],
    },
    {
      key: 'nsg_enabled',
      label: 'Network Security Group',
      type: 'boolean',
      required: false,
      group: 'Security',
      order: 10,
      defaultValue: false,
      description: 'Associate a Network Security Group with this subnet',
    },
    {
      key: 'nsg_id',
      label: 'NSG',
      type: 'reference',
      required: false,
      group: 'Security',
      order: 11,
      referenceTargetTypes: ['azurerm/networking/network_security_group'],
      visibleWhen: { field: 'nsg_enabled', operator: 'truthy' },
    },
    {
      key: 'route_table_enabled',
      label: 'Route Table',
      type: 'boolean',
      required: false,
      group: 'Routing',
      order: 20,
      defaultValue: false,
      description: 'Associate a Route Table (UDR) with this subnet',
    },
    {
      key: 'route_table_id',
      label: 'Route Table',
      type: 'reference',
      required: false,
      group: 'Routing',
      order: 21,
      referenceTargetTypes: ['azurerm/networking/route_table'],
      visibleWhen: { field: 'route_table_enabled', operator: 'truthy' },
    },
    {
      key: 'nat_gateway_enabled',
      label: 'NAT Gateway',
      type: 'boolean',
      required: false,
      group: 'Routing',
      order: 22,
      defaultValue: false,
      description: 'Associate a NAT Gateway for outbound internet traffic',
    },
    {
      key: 'nat_gateway_id',
      label: 'NAT Gateway',
      type: 'reference',
      required: false,
      group: 'Routing',
      order: 23,
      referenceTargetTypes: ['azurerm/networking/nat_gateway'],
      visibleWhen: { field: 'nat_gateway_enabled', operator: 'truthy' },
    },
    {
      key: 'delegation_enabled',
      label: 'Service Delegation',
      type: 'boolean',
      required: false,
      group: 'Delegation',
      order: 30,
      defaultValue: false,
      description: 'Delegate this subnet to an Azure service (e.g. App Service VNet integration, Container Instances)',
    },
    {
      key: 'delegation_service',
      label: 'Delegated Service',
      type: 'select',
      required: false,
      group: 'Delegation',
      order: 31,
      defaultValue: 'Microsoft.Web/serverFarms',
      visibleWhen: { field: 'delegation_enabled', operator: 'truthy' },
      options: [
        { label: 'App Service / Functions (VNet Integration)', value: 'Microsoft.Web/serverFarms' },
        { label: 'Container Instances', value: 'Microsoft.ContainerInstance/containerGroups' },
        { label: 'Azure Databricks', value: 'Microsoft.Databricks/workspaces' },
        { label: 'API Management', value: 'Microsoft.ApiManagement/service' },
      ],
    },
  ],

  parentReference: { propertyKey: 'virtual_network_name' },

  handles: [],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
  ],

  costEstimation: { serviceName: 'Subnet', staticMonthlyCost: 0 },
};
