import type { ResourceSchema } from '@terrastudio/types';

export const keyVaultSecretSchema: ResourceSchema = {
  typeId: 'azurerm/security/key_vault_secret',
  provider: 'azurerm',
  displayName: 'Key Vault Secret',
  category: 'security',
  description: 'A secret stored in Azure Key Vault',
  terraformType: 'azurerm_key_vault_secret',
  supportsTags: true,
  requiresResourceGroup: false,
  canBeChildOf: ['azurerm/security/key_vault'],
  parentReference: { propertyKey: 'key_vault_id' },
  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'my-secret',
      group: 'General',
      order: 1,
      validation: {
        minLength: 1,
        maxLength: 127,
        pattern: '^[a-zA-Z0-9-]+$',
        patternMessage: 'Alphanumerics and hyphens only',
      },
    },
    {
      key: 'value',
      label: 'Value',
      type: 'string',
      required: true,
      sensitive: true,
      group: 'General',
      order: 2,
      description: 'Will be stored as a sensitive Terraform variable',
    },
    {
      key: 'content_type',
      label: 'Content Type',
      type: 'string',
      required: false,
      group: 'General',
      order: 3,
      placeholder: 'text/plain',
      description: 'MIME type of the secret value',
    },
    {
      key: 'expiration_date',
      label: 'Expiration Date',
      type: 'string',
      required: false,
      group: 'General',
      order: 4,
      placeholder: '2025-12-31T00:00:00Z',
      description: 'ISO 8601 date when the secret expires',
    },
  ],
  handles: [],
  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'version', label: 'Version', terraformAttribute: 'version' },
    { key: 'versionless_id', label: 'Versionless ID', terraformAttribute: 'versionless_id' },
  ],
};
