import type { ResourceSchema } from '@terrastudio/types';

export const cdnEndpointSchema: ResourceSchema = {
  typeId: 'azurerm/web/cdn_endpoint',
  provider: 'azurerm',
  displayName: 'CDN Endpoint',
  category: 'web',
  description: 'An endpoint within an Azure CDN profile',
  terraformType: 'azurerm_cdn_endpoint',
  supportsTags: true,
  requiresResourceGroup: true,
  canBeChildOf: ['azurerm/web/cdn_profile'],
  parentReference: { propertyKey: 'profile_name' },
  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'cdn-endpoint-myapp',
      group: 'General',
      order: 1,
      validation: { minLength: 1, maxLength: 260 },
    },
    {
      key: 'origin_host_name',
      label: 'Origin Host Name',
      type: 'string',
      required: true,
      placeholder: 'www.example.com',
      group: 'General',
      order: 2,
      description: 'The host name of the origin server',
    },
    {
      key: 'is_http_allowed',
      label: 'HTTP Allowed',
      type: 'boolean',
      required: false,
      group: 'Settings',
      order: 3,
      defaultValue: true,
      description: 'Allow HTTP traffic',
    },
    {
      key: 'is_https_allowed',
      label: 'HTTPS Allowed',
      type: 'boolean',
      required: false,
      group: 'Settings',
      order: 4,
      defaultValue: true,
      description: 'Allow HTTPS traffic',
    },
    {
      key: 'is_compression_enabled',
      label: 'Enable Compression',
      type: 'boolean',
      required: false,
      group: 'Optimization',
      order: 5,
      defaultValue: false,
      description: 'Enable content compression',
    },
    {
      key: 'content_types_to_compress',
      label: 'Content Types to Compress',
      type: 'array',
      required: false,
      group: 'Optimization',
      order: 6,
      visibleWhen: { field: 'is_compression_enabled', operator: 'truthy' },
      itemSchema: { key: 'type', label: 'Content Type', type: 'string', required: true, placeholder: 'application/json' },
    },
    {
      key: 'querystring_caching_behaviour',
      label: 'Query String Caching',
      type: 'select',
      required: false,
      group: 'Settings',
      order: 7,
      defaultValue: 'IgnoreQueryString',
      options: [
        { label: 'Ignore Query String', value: 'IgnoreQueryString' },
        { label: 'Bypass Caching', value: 'BypassCaching' },
        { label: 'Use Query String', value: 'UseQueryString' },
      ],
    },
  ],
  handles: [],
  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'fqdn', label: 'FQDN', terraformAttribute: 'fqdn' },
    { key: 'host_name', label: 'Host Name', terraformAttribute: 'host_name' },
  ],

  costEstimation: {
    serviceName: 'Content Delivery Network',
    staticMonthlyCost: 0,
  },
};
