import type { ResourceSchema } from '@terrastudio/types';

export const storageAccountSchema: ResourceSchema = {
  typeId: 'azurerm/storage/storage_account',
  provider: 'azurerm',
  displayName: 'Storage Account',
  category: 'storage',
  description: 'Azure Storage Account for blobs, files, queues, and tables',
  terraformType: 'azurerm_storage_account',
  supportsTags: true,
  requiresResourceGroup: true,
  cafAbbreviation: 'st',
  namingConstraints: { lowercase: true, noHyphens: true, maxLength: 24 },
  isContainer: true,
  canBeChildOf: [
    'azurerm/core/resource_group',
    'azurerm/networking/subnet',
  ],
  visualContainment: true,
  privateEndpointConfig: {
    subresources: [
      { key: 'blob', label: 'Blob Storage' },
      { key: 'file', label: 'File Storage' },
      { key: 'queue', label: 'Queue Storage' },
      { key: 'table', label: 'Table Storage' },
    ],
    defaultSubresource: 'blob',
  },
  containerStyle: {
    borderColor: '#2B7CF6',
    borderStyle: 'dotted',
    backgroundColor: '#ffffff',
    headerColor: '#1a1a2e',
    borderRadius: 12,
    borderWidth: 3,
    hideHeaderBorder: true,
    iconSize: 28,
    labelSize: 16,
    dashArray: '4,8',
  },
  minSize: { width: 250, height: 180 },

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'mystorageaccount',
      group: 'General',
      order: 1,
      validation: {
        minLength: 3,
        maxLength: 24,
        pattern: '^[a-z0-9]+$',
        patternMessage: 'Must be 3-24 lowercase letters and numbers only',
      },
    },
    {
      key: 'account_tier',
      label: 'Account Tier',
      type: 'select',
      required: true,
      group: 'General',
      order: 2,
      defaultValue: 'Standard',
      options: [
        { label: 'Standard', value: 'Standard' },
        { label: 'Premium', value: 'Premium' },
      ],
    },
    {
      key: 'account_replication_type',
      label: 'Replication',
      type: 'select',
      required: true,
      group: 'General',
      order: 3,
      defaultValue: 'LRS',
      options: [
        { label: 'LRS (Locally Redundant)', value: 'LRS' },
        { label: 'GRS (Geo-Redundant)', value: 'GRS' },
        { label: 'RAGRS (Read-Access Geo-Redundant)', value: 'RAGRS' },
        { label: 'ZRS (Zone-Redundant)', value: 'ZRS' },
        { label: 'GZRS (Geo-Zone-Redundant)', value: 'GZRS' },
        { label: 'RAGZRS (Read-Access Geo-Zone-Redundant)', value: 'RAGZRS' },
      ],
    },
    {
      key: 'account_kind',
      label: 'Account Kind',
      type: 'select',
      required: false,
      group: 'Advanced',
      order: 4,
      defaultValue: 'StorageV2',
      options: [
        { label: 'StorageV2 (General Purpose v2)', value: 'StorageV2' },
        { label: 'BlobStorage', value: 'BlobStorage' },
        { label: 'Storage (General Purpose v1)', value: 'Storage' },
      ],
    },
    {
      key: 'access_tier',
      label: 'Access Tier',
      type: 'select',
      required: false,
      group: 'Advanced',
      order: 5,
      defaultValue: 'Hot',
      options: [
        { label: 'Hot', value: 'Hot' },
        { label: 'Cool', value: 'Cool' },
      ],
    },
    {
      key: 'min_tls_version',
      label: 'Minimum TLS Version',
      type: 'select',
      required: false,
      group: 'Security',
      order: 6,
      defaultValue: 'TLS1_2',
      options: [
        { label: 'TLS 1.2', value: 'TLS1_2' },
        { label: 'TLS 1.1', value: 'TLS1_1' },
        { label: 'TLS 1.0', value: 'TLS1_0' },
      ],
    },
    {
      key: 'https_traffic_only_enabled',
      label: 'HTTPS Only',
      type: 'boolean',
      required: false,
      group: 'Security',
      order: 7,
      defaultValue: true,
    },
    {
      key: 'shared_access_key_enabled',
      label: 'Shared Access Key Enabled',
      type: 'boolean',
      required: false,
      group: 'Security',
      order: 8,
      defaultValue: true,
      description: 'Allow access via shared access keys',
    },
    {
      key: 'public_network_access_enabled',
      label: 'Public Network Access',
      type: 'boolean',
      required: false,
      group: 'Security',
      order: 9,
      defaultValue: true,
    },
    {
      key: 'infrastructure_encryption_enabled',
      label: 'Infrastructure Encryption',
      type: 'boolean',
      required: false,
      group: 'Security',
      order: 10,
      defaultValue: false,
      description: 'Double encryption for data at rest',
    },
    {
      key: 'identity_enabled',
      label: 'Enable Identity',
      type: 'boolean',
      required: false,
      group: 'Identity',
      order: 11,
      defaultValue: false,
    },
    {
      key: 'identity_type',
      label: 'Identity Type',
      type: 'select',
      required: false,
      group: 'Identity',
      order: 12,
      defaultValue: 'SystemAssigned',
      visibleWhen: { field: 'identity_enabled', operator: 'truthy' },
      options: [
        { label: 'System Assigned', value: 'SystemAssigned' },
        { label: 'User Assigned', value: 'UserAssigned' },
        { label: 'System & User Assigned', value: 'SystemAssigned, UserAssigned' },
      ],
    },
    {
      key: 'versioning_enabled',
      label: 'Blob Versioning',
      type: 'boolean',
      required: false,
      group: 'Data Protection',
      order: 13,
      defaultValue: false,
    },
    {
      key: 'delete_retention_days',
      label: 'Blob Soft Delete (days)',
      type: 'number',
      required: false,
      group: 'Data Protection',
      order: 14,
      defaultValue: 7,
      validation: { min: 1, max: 365 },
    },
    {
      key: 'container_delete_retention_days',
      label: 'Container Soft Delete (days)',
      type: 'number',
      required: false,
      group: 'Data Protection',
      order: 15,
      defaultValue: 7,
      validation: { min: 1, max: 365 },
    },
    {
      key: 'network_default_action',
      label: 'Default Network Action',
      type: 'select',
      required: false,
      group: 'Network Rules',
      order: 16,
      defaultValue: 'Allow',
      options: [
        { label: 'Allow', value: 'Allow' },
        { label: 'Deny', value: 'Deny' },
      ],
    },
    {
      key: 'network_bypass',
      label: 'Bypass',
      type: 'multiselect',
      required: false,
      group: 'Network Rules',
      order: 17,
      defaultValue: ['AzureServices'],
      visibleWhen: { field: 'network_default_action', operator: 'eq', value: 'Deny' },
      options: [
        { label: 'Azure Services', value: 'AzureServices' },
        { label: 'Logging', value: 'Logging' },
        { label: 'Metrics', value: 'Metrics' },
        { label: 'None', value: 'None' },
      ],
    },
  ],

  handles: [
    {
      id: 'pep-target',
      type: 'target',
      position: 'left',
      label: 'Private Endpoint',
    },
  ],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    {
      key: 'primary_connection_string',
      label: 'Connection String',
      terraformAttribute: 'primary_connection_string',
      sensitive: true,
    },
    {
      key: 'primary_access_key',
      label: 'Access Key',
      terraformAttribute: 'primary_access_key',
      sensitive: true,
    },
    { key: 'primary_blob_endpoint', label: 'Blob Endpoint', terraformAttribute: 'primary_blob_endpoint' },
  ],

  costEstimation: {
    serviceName: 'Storage',
    skuProperty: 'account_tier',
    usageInputs: [
      {
        key: '_cost_storage_gb',
        label: 'Estimated Storage',
        unit: 'GB',
        defaultValue: 100,
        min: 1,
        max: 1000000,
        description: 'Total data stored across all containers/shares',
      },
    ],
  },
};
