import type { ResourceSchema } from '@terrastudio/types';

export const apiManagementSchema: ResourceSchema = {
  typeId: 'azurerm/integration/api_management',
  provider: 'azurerm',
  displayName: 'API Management',
  category: 'integration',
  description: 'Azure API Management — publish, secure, transform, maintain, and monitor APIs',
  terraformType: 'azurerm_api_management',
  supportsTags: true,
  requiresResourceGroup: true,
  cafAbbreviation: 'apim',
  namingConstraints: { maxLength: 50 },

  canBeChildOf: [
    'azurerm/core/resource_group',
  ],

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'apim-myapp-dev',
      group: 'General',
      order: 1,
      validation: {
        minLength: 1,
        maxLength: 50,
        pattern: '^[a-zA-Z][a-zA-Z0-9-]*[a-zA-Z0-9]$',
        patternMessage: 'Must start with a letter, end with alphanumeric, contain only letters, digits, and hyphens',
      },
    },
    {
      key: 'publisher_name',
      label: 'Publisher Name',
      type: 'string',
      required: true,
      placeholder: 'My Company',
      group: 'General',
      order: 2,
    },
    {
      key: 'publisher_email',
      label: 'Publisher Email',
      type: 'string',
      required: true,
      placeholder: 'admin@example.com',
      group: 'General',
      order: 3,
    },
    {
      key: 'sku_name',
      label: 'SKU',
      type: 'select',
      required: true,
      group: 'General',
      order: 4,
      defaultValue: 'Developer_1',
      options: [
        { label: 'Consumption (0 units)', value: 'Consumption_0' },
        { label: 'Developer (1 unit)', value: 'Developer_1' },
        { label: 'Basic (1 unit)', value: 'Basic_1' },
        { label: 'Basic (2 units)', value: 'Basic_2' },
        { label: 'Standard (1 unit)', value: 'Standard_1' },
        { label: 'Standard (2 units)', value: 'Standard_2' },
        { label: 'Premium (1 unit)', value: 'Premium_1' },
        { label: 'Premium (2 units)', value: 'Premium_2' },
        { label: 'Premium (3 units)', value: 'Premium_3' },
      ],
    },
    {
      key: 'virtual_network_type',
      label: 'VNet Integration',
      type: 'select',
      required: false,
      group: 'Network',
      order: 10,
      defaultValue: 'None',
      options: [
        { label: 'None', value: 'None' },
        { label: 'Internal', value: 'Internal' },
        { label: 'External', value: 'External' },
      ],
      description: 'VNet integration mode. Internal: accessible only from within VNet. External: gateway accessible from internet.',
    },
    {
      key: 'subnet_id',
      label: 'Subnet',
      type: 'reference',
      required: false,
      group: 'Network',
      order: 11,
      referenceTargetTypes: ['azurerm/networking/subnet'],
      description: 'Subnet for VNet integration (required when VNet type is Internal or External)',
    },
    {
      key: 'public_network_access_enabled',
      label: 'Public Network Access',
      type: 'boolean',
      required: false,
      group: 'Network',
      order: 12,
      defaultValue: true,
      description: 'Allow public access to the API Management service',
    },
    {
      key: 'protocols',
      label: 'Client Protocols',
      type: 'multiselect',
      required: false,
      group: 'Protocols',
      order: 15,
      defaultValue: ['https'],
      options: [
        { label: 'HTTPS', value: 'https' },
        { label: 'HTTP', value: 'http' },
      ],
      description: 'Protocols enabled for client-side access',
    },
    {
      key: 'client_certificate_enabled',
      label: 'Client Certificate Authentication',
      type: 'boolean',
      required: false,
      group: 'Security',
      order: 16,
      defaultValue: false,
    },
    {
      key: 'gateway_disabled',
      label: 'Gateway Disabled',
      type: 'boolean',
      required: false,
      group: 'Security',
      order: 17,
      defaultValue: false,
      description: 'Disable gateway for consumption-tier APIM',
    },
    {
      key: 'notification_sender_email',
      label: 'Notification Sender Email',
      type: 'string',
      required: false,
      group: 'Notifications',
      order: 18,
      placeholder: 'apim@example.com',
    },
    {
      key: 'identity_enabled',
      label: 'Managed Identity',
      type: 'boolean',
      required: false,
      group: 'Identity',
      order: 19,
      defaultValue: false,
    },
    {
      key: 'identity_type',
      label: 'Identity Type',
      type: 'select',
      required: false,
      group: 'Identity',
      order: 20,
      defaultValue: 'SystemAssigned',
      visibleWhen: { field: 'identity_enabled', operator: 'truthy' },
      options: [
        { label: 'System Assigned', value: 'SystemAssigned' },
        { label: 'User Assigned', value: 'UserAssigned' },
        { label: 'System + User Assigned', value: 'SystemAssigned, UserAssigned' },
      ],
    },
    {
      key: 'min_api_version',
      label: 'Minimum API Version',
      type: 'string',
      required: false,
      group: 'Advanced',
      order: 30,
      placeholder: '2019-12-01',
      description: 'Minimum allowed API version for control plane API calls',
    },
    {
      key: 'zones',
      label: 'Availability Zones',
      type: 'array',
      required: false,
      group: 'Availability',
      order: 40,
      description: 'Availability zones (Premium SKU only, e.g., 1, 2, 3)',
    },
  ],

  handles: [
    {
      id: 'pep-target',
      type: 'target',
      position: 'left',
      label: 'Private Endpoint',
    },
  ],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'gateway_url', label: 'Gateway URL', terraformAttribute: 'gateway_url' },
    { key: 'management_api_url', label: 'Management API URL', terraformAttribute: 'management_api_url' },
    { key: 'portal_url', label: 'Developer Portal URL', terraformAttribute: 'portal_url' },
    { key: 'public_ip_addresses', label: 'Public IP Addresses', terraformAttribute: 'public_ip_addresses' },
    { key: 'private_ip_addresses', label: 'Private IP Addresses', terraformAttribute: 'private_ip_addresses' },
  ],

  costEstimation: {
    serviceName: 'API Management',
    skuProperty: 'sku_name',
    usageInputs: [
      {
        key: '_cost_api_calls',
        label: 'API Calls',
        unit: 'calls/mo (thousands)',
        defaultValue: 1000,
        min: 0,
        max: 100000000,
        description: 'Estimated monthly API calls (in thousands). Consumption tier charges per call; other tiers have flat pricing.',
      },
    ],
  },
};
