import type { ResourceSchema } from '@terrastudio/types';

export const ec2InstanceSchema: ResourceSchema = {
  typeId: 'aws/compute/instance',
  provider: 'aws',
  displayName: 'EC2 Instance',
  category: 'aws-compute',
  description: 'AWS EC2 Virtual Machine instance',
  terraformType: 'aws_instance',
  supportsTags: true,
  requiresResourceGroup: false,
  canBeChildOf: ['aws/networking/subnet'],
  parentReference: { propertyKey: 'subnet_id' },

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'web-server-01',
      group: 'General',
      order: 1,
    },
    {
      key: 'ami',
      label: 'AMI',
      type: 'string',
      required: true,
      placeholder: 'ami-0c55b159cbfafe1f0',
      group: 'General',
      order: 2,
    },
    {
      key: 'instance_type',
      label: 'Instance Type',
      type: 'select',
      required: true,
      defaultValue: 't3.micro',
      group: 'General',
      order: 3,
      options: [
        { label: 't2.micro', value: 't2.micro' },
        { label: 't2.small', value: 't2.small' },
        { label: 't2.medium', value: 't2.medium' },
        { label: 't3.micro', value: 't3.micro' },
        { label: 't3.small', value: 't3.small' },
        { label: 't3.medium', value: 't3.medium' },
        { label: 't3.large', value: 't3.large' },
        { label: 'm5.large', value: 'm5.large' },
        { label: 'm5.xlarge', value: 'm5.xlarge' },
        { label: 'c5.large', value: 'c5.large' },
        { label: 'c5.xlarge', value: 'c5.xlarge' },
        { label: 'r5.large', value: 'r5.large' },
      ],
    },
    {
      key: 'key_name',
      label: 'Key Pair Name',
      type: 'string',
      required: false,
      placeholder: 'my-key-pair',
      group: 'General',
      order: 4,
    },
    {
      key: 'associate_public_ip_address',
      label: 'Associate Public IP',
      type: 'boolean',
      required: false,
      defaultValue: false,
      group: 'Networking',
      order: 5,
    },
    {
      key: 'sg_enabled',
      label: 'Security Group',
      type: 'boolean',
      required: false,
      defaultValue: false,
      description: 'Associate a Security Group',
      group: 'Security',
      order: 6,
    },
    {
      key: 'security_group_ids',
      label: 'Security Group',
      type: 'reference',
      required: false,
      referenceTargetTypes: ['aws/compute/security_group'],
      group: 'Security',
      order: 7,
      visibleWhen: { field: 'sg_enabled', operator: 'truthy' },
    },
    {
      key: 'root_block_device_size',
      label: 'Root Volume Size (GB)',
      type: 'number',
      required: false,
      defaultValue: 8,
      description: 'Root volume size (GB)',
      group: 'Storage',
      order: 8,
    },
    {
      key: 'root_block_device_type',
      label: 'Root Volume Type',
      type: 'select',
      required: false,
      defaultValue: 'gp3',
      group: 'Storage',
      order: 9,
      options: [
        { label: 'gp3', value: 'gp3' },
        { label: 'gp2', value: 'gp2' },
        { label: 'io1', value: 'io1' },
        { label: 'io2', value: 'io2' },
        { label: 'st1', value: 'st1' },
        { label: 'sc1', value: 'sc1' },
      ],
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'Instance ID', terraformAttribute: 'id' },
    { key: 'arn', label: 'ARN', terraformAttribute: 'arn' },
    { key: 'public_ip', label: 'Public IP', terraformAttribute: 'public_ip' },
    { key: 'private_ip', label: 'Private IP', terraformAttribute: 'private_ip' },
    { key: 'public_dns', label: 'Public DNS', terraformAttribute: 'public_dns' },
    { key: 'private_dns', label: 'Private DNS', terraformAttribute: 'private_dns' },
  ],

  costEstimation: {
    serviceName: 'EC2',
    skuProperty: 'instance_type',
  },
};
