import type { ResourceSchema } from '@terrastudio/types';

export const frontdoorProfileSchema: ResourceSchema = {
  typeId: 'azurerm/web/frontdoor_profile',
  provider: 'azurerm',
  displayName: 'Front Door Profile',
  category: 'web',
  description: 'Azure Front Door profile for global load balancing and CDN',
  terraformType: 'azurerm_cdn_frontdoor_profile',
  supportsTags: true,
  requiresResourceGroup: true,
  canBeChildOf: ['azurerm/core/resource_group'],
  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'fd-myapp',
      group: 'General',
      order: 1,
      validation: { minLength: 1, maxLength: 260 },
    },
    {
      key: 'sku_name',
      label: 'SKU',
      type: 'select',
      required: true,
      group: 'General',
      order: 2,
      defaultValue: 'Standard_AzureFrontDoor',
      options: [
        { label: 'Standard', value: 'Standard_AzureFrontDoor' },
        { label: 'Premium', value: 'Premium_AzureFrontDoor' },
      ],
    },
    {
      key: 'response_timeout_seconds',
      label: 'Response Timeout (seconds)',
      type: 'number',
      required: false,
      group: 'Settings',
      order: 3,
      defaultValue: 120,
      description: 'Timeout in seconds for backend responses',
      validation: { min: 16, max: 240 },
    },
    {
      key: 'identity_enabled',
      label: 'Enable Identity',
      type: 'boolean',
      required: false,
      group: 'Identity',
      order: 4,
      defaultValue: false,
    },
    {
      key: 'identity_type',
      label: 'Identity Type',
      type: 'select',
      required: false,
      group: 'Identity',
      order: 5,
      defaultValue: 'SystemAssigned',
      visibleWhen: { field: 'identity_enabled', operator: 'truthy' },
      options: [
        { label: 'System Assigned', value: 'SystemAssigned' },
        { label: 'User Assigned', value: 'UserAssigned' },
        { label: 'System & User Assigned', value: 'SystemAssigned, UserAssigned' },
      ],
    },
  ],
  handles: [],
  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'resource_guid', label: 'Resource GUID', terraformAttribute: 'resource_guid' },
    { key: 'principal_id', label: 'Principal ID', terraformAttribute: 'identity[0].principal_id' },
    { key: 'tenant_id', label: 'Tenant ID', terraformAttribute: 'identity[0].tenant_id' },
  ],

  costEstimation: {
    serviceName: 'Front Door',
    skuProperty: 'sku_name',
    usageInputs: [
      {
        key: '_cost_data_gb',
        label: 'Data Transfer',
        unit: 'GB/mo',
        defaultValue: 100,
        min: 0,
        max: 1000000,
        description: 'Monthly data routed and transferred (~$0.018–$0.024/GB routing + $0.009–$0.012/GB transfer)',
      },
    ],
  },
};
