import type { ResourceSchema } from '@terrastudio/types';

export const dynamodbTableSchema: ResourceSchema = {
  typeId: 'aws/database/dynamodb_table',
  provider: 'aws',
  displayName: 'DynamoDB Table',
  category: 'aws-database',
  description: 'AWS DynamoDB NoSQL table',
  terraformType: 'aws_dynamodb_table',
  supportsTags: true,
  requiresResourceGroup: false,

  properties: [
    {
      key: 'name',
      label: 'Table Name',
      type: 'string',
      required: true,
      placeholder: 'my-table',
      group: 'General',
      order: 1,
    },
    {
      key: 'billing_mode',
      label: 'Billing Mode',
      type: 'select',
      required: true,
      defaultValue: 'PAY_PER_REQUEST',
      group: 'General',
      order: 2,
      options: [
        { label: 'On-Demand (Pay per Request)', value: 'PAY_PER_REQUEST' },
        { label: 'Provisioned', value: 'PROVISIONED' },
      ],
    },
    {
      key: 'hash_key',
      label: 'Partition Key',
      type: 'string',
      required: true,
      defaultValue: 'id',
      placeholder: 'id',
      group: 'Keys',
      order: 3,
    },
    {
      key: 'hash_key_type',
      label: 'Partition Key Type',
      type: 'select',
      required: true,
      defaultValue: 'S',
      group: 'Keys',
      order: 4,
      options: [
        { label: 'String', value: 'S' },
        { label: 'Number', value: 'N' },
        { label: 'Binary', value: 'B' },
      ],
    },
    {
      key: 'range_key',
      label: 'Sort Key',
      type: 'string',
      required: false,
      placeholder: 'timestamp',
      group: 'Keys',
      order: 5,
    },
    {
      key: 'range_key_type',
      label: 'Sort Key Type',
      type: 'select',
      required: false,
      defaultValue: 'S',
      group: 'Keys',
      order: 6,
      visibleWhen: { field: 'range_key', operator: 'truthy' },
      options: [
        { label: 'String', value: 'S' },
        { label: 'Number', value: 'N' },
        { label: 'Binary', value: 'B' },
      ],
    },
    {
      key: 'read_capacity',
      label: 'Read Capacity Units',
      type: 'number',
      required: false,
      defaultValue: 5,
      group: 'Provisioned Capacity',
      order: 7,
      visibleWhen: { field: 'billing_mode', operator: 'eq', value: 'PROVISIONED' },
      validation: { min: 1 },
    },
    {
      key: 'write_capacity',
      label: 'Write Capacity Units',
      type: 'number',
      required: false,
      defaultValue: 5,
      group: 'Provisioned Capacity',
      order: 8,
      visibleWhen: { field: 'billing_mode', operator: 'eq', value: 'PROVISIONED' },
      validation: { min: 1 },
    },
    {
      key: 'point_in_time_recovery',
      label: 'Point-in-Time Recovery',
      type: 'boolean',
      required: false,
      defaultValue: false,
      group: 'Settings',
      order: 9,
    },
    {
      key: 'ttl_enabled',
      label: 'Enable TTL',
      type: 'boolean',
      required: false,
      defaultValue: false,
      group: 'TTL',
      order: 10,
    },
    {
      key: 'ttl_attribute_name',
      label: 'TTL Attribute Name',
      type: 'string',
      required: false,
      placeholder: 'expires_at',
      group: 'TTL',
      order: 11,
      visibleWhen: { field: 'ttl_enabled', operator: 'truthy' },
    },
    {
      key: 'stream_enabled',
      label: 'Enable Streams',
      type: 'boolean',
      required: false,
      defaultValue: false,
      group: 'Streams',
      order: 12,
    },
    {
      key: 'stream_view_type',
      label: 'Stream View Type',
      type: 'select',
      required: false,
      group: 'Streams',
      order: 13,
      visibleWhen: { field: 'stream_enabled', operator: 'truthy' },
      options: [
        { label: 'New Image', value: 'NEW_IMAGE' },
        { label: 'Old Image', value: 'OLD_IMAGE' },
        { label: 'New and Old Images', value: 'NEW_AND_OLD_IMAGES' },
        { label: 'Keys Only', value: 'KEYS_ONLY' },
      ],
    },
    {
      key: 'global_secondary_indexes',
      label: 'Global Secondary Indexes',
      type: 'array',
      required: false,
      description: 'GSIs for alternative query patterns',
      group: 'Indexes',
      order: 14,
      itemSchema: {
        key: 'gsi',
        label: 'Global Secondary Index',
        type: 'object',
        required: true,
        nestedSchema: [
          {
            key: 'name',
            label: 'Index Name',
            type: 'string',
            required: true,
            placeholder: 'my-index',
          },
          {
            key: 'hash_key',
            label: 'Partition Key',
            type: 'string',
            required: true,
            placeholder: 'attribute_name',
          },
          {
            key: 'range_key',
            label: 'Sort Key',
            type: 'string',
            required: false,
            placeholder: 'attribute_name',
          },
          {
            key: 'projection_type',
            label: 'Projection Type',
            type: 'select',
            required: true,
            options: [
              { label: 'All', value: 'ALL' },
              { label: 'Keys Only', value: 'KEYS_ONLY' },
              { label: 'Include', value: 'INCLUDE' },
            ],
          },
          {
            key: 'read_capacity',
            label: 'Read Capacity Units',
            type: 'number',
            required: false,
          },
          {
            key: 'write_capacity',
            label: 'Write Capacity Units',
            type: 'number',
            required: false,
          },
        ],
      },
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'Table ID', terraformAttribute: 'id' },
    { key: 'arn', label: 'ARN', terraformAttribute: 'arn' },
    { key: 'name', label: 'Table Name', terraformAttribute: 'name' },
    { key: 'stream_arn', label: 'Stream ARN', terraformAttribute: 'stream_arn' },
  ],

  costEstimation: {
    serviceName: 'DynamoDB',
    usageInputs: [
      {
        key: '_cost_storage_gb',
        label: 'Estimated Storage',
        unit: 'GB',
        defaultValue: 1,
        min: 0,
        max: 1000000,
        description: 'Total data stored (~$0.25/GB/month)',
      },
      {
        key: '_cost_wcu',
        label: 'Write Request Units',
        unit: 'million/mo',
        defaultValue: 1,
        min: 0,
        max: 100000,
        description: 'On-Demand: ~$1.25/million WRU. Provisioned: ~$0.47/WCU/month.',
      },
      {
        key: '_cost_rcu',
        label: 'Read Request Units',
        unit: 'million/mo',
        defaultValue: 1,
        min: 0,
        max: 100000,
        description: 'On-Demand: ~$0.25/million RRU. Provisioned: ~$0.09/RCU/month.',
      },
    ],
  },
};
