import type { ResourceSchema } from '@terrastudio/types';

export const ecsServiceSchema: ResourceSchema = {
  typeId: 'aws/containers/ecs_service',
  provider: 'aws',
  displayName: 'ECS Service',
  category: 'aws-containers',
  description: 'ECS Service — runs and maintains desired count of tasks',
  terraformType: 'aws_ecs_service',
  supportsTags: true,
  requiresResourceGroup: false,
  canBeChildOf: ['aws/containers/ecs_cluster'],
  parentReference: { propertyKey: 'cluster' },

  properties: [
    {
      key: 'name',
      label: 'Service Name',
      type: 'string',
      required: true,
      placeholder: 'my-service',
      group: 'General',
      order: 1,
    },
    {
      key: 'desired_count',
      label: 'Desired Count',
      type: 'number',
      required: true,
      defaultValue: 1,
      group: 'General',
      order: 2,
      validation: { min: 0, max: 5000 },
      description: 'Number of task instances to keep running',
    },
    {
      key: 'launch_type',
      label: 'Launch Type',
      type: 'select',
      required: false,
      defaultValue: 'FARGATE',
      options: [
        { label: 'Fargate', value: 'FARGATE' },
        { label: 'EC2', value: 'EC2' },
      ],
      group: 'General',
      order: 3,
    },
    // --- Network group ---
    {
      key: 'subnet_ids',
      label: 'Subnet IDs',
      type: 'array',
      required: false,
      group: 'Network',
      order: 4,
      itemSchema: { key: 'id', label: 'Subnet ID', type: 'string', required: true },
      description: 'List of subnet IDs for the awsvpc network configuration',
    },
    {
      key: 'security_group_ids',
      label: 'Security Group IDs',
      type: 'array',
      required: false,
      group: 'Network',
      order: 5,
      itemSchema: { key: 'id', label: 'Security Group ID', type: 'string', required: true },
      description: 'List of security group IDs for the awsvpc network configuration',
    },
    {
      key: 'assign_public_ip',
      label: 'Assign Public IP',
      type: 'boolean',
      required: false,
      defaultValue: false,
      group: 'Network',
      order: 6,
      description: 'Assign a public IP address to the task ENI (Fargate only)',
    },
    // --- Load Balancer group ---
    {
      key: 'lb_target_group_arn',
      label: 'Target Group ARN',
      type: 'string',
      required: false,
      group: 'Load Balancer',
      order: 7,
      description: 'ARN of the ALB/NLB target group',
    },
    {
      key: 'lb_container_name',
      label: 'Container Name',
      type: 'string',
      required: false,
      group: 'Load Balancer',
      order: 8,
      description: 'Container name to associate with the target group',
      visibleWhen: { field: 'lb_target_group_arn', operator: 'truthy' },
    },
    {
      key: 'lb_container_port',
      label: 'Container Port',
      type: 'number',
      required: false,
      group: 'Load Balancer',
      order: 9,
      description: 'Container port to associate with the target group',
      visibleWhen: { field: 'lb_target_group_arn', operator: 'truthy' },
    },
    {
      key: 'health_check_grace_period',
      label: 'Health Check Grace Period (s)',
      type: 'number',
      required: false,
      defaultValue: 0,
      group: 'Load Balancer',
      order: 10,
      validation: { min: 0, max: 7200 },
      description: 'Seconds to wait before checking health of new tasks',
    },
    // --- Deployment group ---
    {
      key: 'deployment_minimum_healthy_percent',
      label: 'Min Healthy %',
      type: 'number',
      required: false,
      defaultValue: 100,
      group: 'Deployment',
      order: 11,
      validation: { min: 0, max: 200 },
      description: 'Lower limit on the number of running tasks during a deployment',
    },
    {
      key: 'deployment_maximum_percent',
      label: 'Max %',
      type: 'number',
      required: false,
      defaultValue: 200,
      group: 'Deployment',
      order: 12,
      validation: { min: 100, max: 400 },
      description: 'Upper limit on the number of running tasks during a deployment',
    },
  ],

  handles: [
    { id: 'service-taskdef', type: 'target', position: 'left', label: 'Task Definition' },
    { id: 'service-out', type: 'source', position: 'right', label: 'Service' },
  ],

  outputs: [
    { key: 'id', label: 'Service ID', terraformAttribute: 'id' },
    { key: 'name', label: 'Service Name', terraformAttribute: 'name' },
  ],

  costEstimation: {
    serviceName: 'Amazon ECS',
    staticMonthlyCost: 0,
  },
};
