import type { ResourceSchema } from '@terrastudio/types';

export const postgresqlFlexibleServerSchema: ResourceSchema = {
  typeId: 'azurerm/database/postgresql_flexible_server',
  provider: 'azurerm',
  displayName: 'PostgreSQL Flexible Server',
  category: 'postgresql',
  description: 'Azure Database for PostgreSQL Flexible Server — fully managed relational database',
  terraformType: 'azurerm_postgresql_flexible_server',
  supportsTags: true,
  requiresResourceGroup: true,
  cafAbbreviation: 'psql',
  namingConstraints: { lowercase: true, maxLength: 63 },
  isContainer: true,

  canBeChildOf: [
    'azurerm/core/resource_group',
  ],

  containerStyle: {
    borderColor: '#2B7CF6',
    borderStyle: 'dotted',
    backgroundColor: '#ffffff',
    headerColor: '#1a1a2e',
    borderRadius: 12,
    borderWidth: 3,
    hideHeaderBorder: true,
    iconSize: 28,
    labelSize: 16,
    dashArray: '4,8',
  },

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'psql-myapp-dev',
      group: 'General',
      order: 1,
      validation: {
        minLength: 3,
        maxLength: 63,
        pattern: '^[a-z0-9][a-z0-9-]*[a-z0-9]$',
        patternMessage: 'Lowercase letters, numbers, and hyphens only',
      },
    },
    {
      key: 'version',
      label: 'PostgreSQL Version',
      type: 'select',
      required: true,
      group: 'General',
      order: 2,
      defaultValue: '16',
      options: [
        { label: '16 (latest)', value: '16' },
        { label: '15', value: '15' },
        { label: '14', value: '14' },
        { label: '13', value: '13' },
        { label: '12', value: '12' },
        { label: '11 (end of life)', value: '11' },
      ],
    },
    {
      key: 'sku_name',
      label: 'SKU',
      type: 'select',
      required: true,
      group: 'General',
      order: 3,
      defaultValue: 'GP_Standard_D2s_v3',
      options: [
        { label: 'B1ms — Burstable (1 vCPU, 2 GB)', value: 'B_Standard_B1ms' },
        { label: 'B2s — Burstable (2 vCPU, 4 GB)', value: 'B_Standard_B2s' },
        { label: 'D2s v3 — General Purpose (2 vCPU, 8 GB)', value: 'GP_Standard_D2s_v3' },
        { label: 'D4s v3 — General Purpose (4 vCPU, 16 GB)', value: 'GP_Standard_D4s_v3' },
        { label: 'D8s v3 — General Purpose (8 vCPU, 32 GB)', value: 'GP_Standard_D8s_v3' },
        { label: 'E4s v3 — Memory Optimized (4 vCPU, 32 GB)', value: 'MO_Standard_E4s_v3' },
        { label: 'E8s v3 — Memory Optimized (8 vCPU, 64 GB)', value: 'MO_Standard_E8s_v3' },
      ],
    },
    {
      key: 'administrator_login',
      label: 'Admin Username',
      type: 'string',
      required: true,
      group: 'Authentication',
      order: 4,
      defaultValue: 'psqladmin',
      placeholder: 'psqladmin',
      validation: {
        minLength: 1,
        maxLength: 63,
      },
    },
    {
      key: 'administrator_password',
      label: 'Admin Password',
      type: 'string',
      required: true,
      sensitive: true,
      group: 'Authentication',
      order: 5,
      description: 'Will be stored as a sensitive Terraform variable',
      validation: {
        minLength: 8,
        maxLength: 128,
      },
    },
    {
      key: 'storage_mb',
      label: 'Storage (MB)',
      type: 'select',
      required: false,
      group: 'Storage',
      order: 6,
      defaultValue: '32768',
      options: [
        { label: '32 GB', value: '32768' },
        { label: '64 GB', value: '65536' },
        { label: '128 GB', value: '131072' },
        { label: '256 GB', value: '262144' },
        { label: '512 GB', value: '524288' },
        { label: '1 TB', value: '1048576' },
      ],
    },
    {
      key: 'backup_retention_days',
      label: 'Backup Retention (days)',
      type: 'number',
      required: false,
      group: 'Storage',
      order: 7,
      defaultValue: 7,
      validation: {
        min: 7,
        max: 35,
      },
    },
    {
      key: 'public_network_access_enabled',
      label: 'Public Network Access',
      type: 'boolean',
      required: false,
      group: 'Security',
      order: 8,
      defaultValue: false,
      description: 'Enable access from the public internet',
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'fqdn', label: 'Fully Qualified Domain Name', terraformAttribute: 'fqdn' },
  ],
};
