import type { ResourceSchema } from '@terrastudio/types';

export const bastionSchema: ResourceSchema = {
  typeId: 'azurerm/networking/bastion_host',
  provider: 'azurerm',
  displayName: 'Azure Bastion',
  category: 'networking',
  description: 'Azure Bastion — secure browser-based RDP/SSH without exposing VMs to the internet',
  terraformType: 'azurerm_bastion_host',
  supportsTags: true,
  requiresResourceGroup: true,
  cafAbbreviation: 'bas',
  namingConstraints: { maxLength: 80 },

  canBeChildOf: [
    'azurerm/core/resource_group',
  ],

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'bas-myapp-dev',
      group: 'General',
      order: 1,
      validation: {
        minLength: 1,
        maxLength: 80,
        pattern: '^[a-zA-Z0-9][a-zA-Z0-9_.-]*[a-zA-Z0-9_]$',
        patternMessage: 'Must start with alphanumeric, end with alphanumeric or underscore',
      },
    },
    {
      key: 'sku',
      label: 'SKU',
      type: 'select',
      required: true,
      group: 'General',
      order: 2,
      defaultValue: 'Basic',
      options: [
        { label: 'Basic', value: 'Basic' },
        { label: 'Standard', value: 'Standard' },
        { label: 'Developer', value: 'Developer' },
      ],
    },
    {
      key: 'copy_paste_enabled',
      label: 'Copy/Paste',
      type: 'boolean',
      required: false,
      group: 'Features',
      order: 10,
      defaultValue: true,
    },
    {
      key: 'file_copy_enabled',
      label: 'File Copy',
      type: 'boolean',
      required: false,
      group: 'Features',
      order: 11,
      defaultValue: false,
      description: 'Enable file copy between client and VM (Standard SKU only)',
      visibleWhen: { field: 'sku', operator: 'eq', value: 'Standard' },
    },
    {
      key: 'tunneling_enabled',
      label: 'Native Client Tunneling',
      type: 'boolean',
      required: false,
      group: 'Features',
      order: 12,
      defaultValue: false,
      description: 'Enable native client (SSH/RDP) tunneling (Standard SKU only)',
      visibleWhen: { field: 'sku', operator: 'eq', value: 'Standard' },
    },
    {
      key: 'scale_units',
      label: 'Scale Units',
      type: 'number',
      required: false,
      group: 'Features',
      order: 13,
      defaultValue: 2,
      description: 'Number of scale units (Standard SKU only, minimum 2)',
      validation: { min: 2, max: 50 },
      visibleWhen: { field: 'sku', operator: 'eq', value: 'Standard' },
    },
    {
      key: 'subnet_id',
      label: 'Subnet',
      type: 'reference',
      required: false,
      group: 'Network',
      order: 20,
      referenceTargetTypes: ['azurerm/networking/subnet'],
      description: 'The subnet must be named "AzureBastionSubnet" with at least /26 CIDR',
    },
    {
      key: 'pip_id',
      label: 'Public IP',
      type: 'reference',
      required: false,
      group: 'Network',
      order: 21,
      referenceTargetTypes: ['azurerm/networking/public_ip'],
      description: 'Standard SKU Public IP address (Static allocation required)',
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'dns_name', label: 'DNS Name', terraformAttribute: 'dns_name' },
  ],

  costEstimation: {
    serviceName: 'Azure Bastion',
    skuProperty: 'sku',
    usageInputs: [
      {
        key: '_cost_outbound_gb',
        label: 'Outbound Data Transfer',
        unit: 'GB/mo',
        defaultValue: 10,
        min: 0,
        max: 100000,
        description: 'First 5 GB/month free, then ~$0.087/GB. Standard SKU additional scale units also add to cost.',
      },
    ],
  },
};
