import type { ResourceSchema } from '@terrastudio/types';

export const eksClusterSchema: ResourceSchema = {
  typeId: 'aws/containers/eks_cluster',
  provider: 'aws',
  displayName: 'EKS Cluster',
  category: 'aws-containers',
  description: 'Amazon Elastic Kubernetes Service — managed Kubernetes control plane',
  terraformType: 'aws_eks_cluster',
  supportsTags: true,
  requiresResourceGroup: false,
  isContainer: true,
  canBeChildOf: [],
  containerStyle: {
    borderColor: '#ED7100',
    borderStyle: 'solid',
    backgroundColor: '#ffffff',
    headerColor: '#232F3E',
    borderRadius: 0,
    borderWidth: 3,
    hideHeaderBorder: true,
    iconSize: 28,
    labelSize: 16,
  },
  minSize: { width: 350, height: 250 },

  properties: [
    {
      key: 'name',
      label: 'Cluster Name',
      type: 'string',
      required: true,
      placeholder: 'my-eks-cluster',
      group: 'General',
      order: 1,
    },
    {
      key: 'kubernetes_version',
      label: 'Kubernetes Version',
      type: 'select',
      required: false,
      defaultValue: '1.29',
      options: [
        { label: '1.29', value: '1.29' },
        { label: '1.28', value: '1.28' },
        { label: '1.27', value: '1.27' },
      ],
      group: 'General',
      order: 2,
    },
    {
      key: 'role_arn',
      label: 'Cluster IAM Role ARN',
      type: 'string',
      required: false,
      placeholder: 'arn:aws:iam::123456789012:role/eks-cluster-role',
      group: 'IAM',
      order: 3,
      description: 'ARN of the IAM role for the EKS cluster',
    },
    {
      key: 'subnet_ids',
      label: 'Subnet IDs',
      type: 'array',
      required: false,
      group: 'Networking',
      order: 4,
      itemSchema: {
        key: 'id',
        label: 'Subnet ID',
        type: 'string',
        required: true,
      },
    },
    {
      key: 'security_group_ids',
      label: 'Security Group IDs',
      type: 'array',
      required: false,
      group: 'Networking',
      order: 5,
      itemSchema: {
        key: 'id',
        label: 'Security Group ID',
        type: 'string',
        required: true,
      },
    },
    {
      key: 'endpoint_private_access',
      label: 'Private Endpoint',
      type: 'boolean',
      required: false,
      defaultValue: false,
      group: 'Networking',
      order: 6,
      description: 'Enable private API server endpoint',
    },
    {
      key: 'endpoint_public_access',
      label: 'Public Endpoint',
      type: 'boolean',
      required: false,
      defaultValue: true,
      group: 'Networking',
      order: 7,
      description: 'Enable public API server endpoint',
    },
    {
      key: 'enabled_cluster_log_types',
      label: 'Cluster Logging',
      type: 'multiselect',
      required: false,
      group: 'Monitoring',
      order: 8,
      options: [
        { label: 'API', value: 'api' },
        { label: 'Audit', value: 'audit' },
        { label: 'Authenticator', value: 'authenticator' },
        { label: 'Controller Manager', value: 'controllerManager' },
        { label: 'Scheduler', value: 'scheduler' },
      ],
    },
  ],

  handles: [
    { id: 'eks-role', type: 'target', position: 'left', label: 'IAM Role' },
    { id: 'eks-out', type: 'source', position: 'right', label: 'Workloads' },
  ],

  outputs: [
    { key: 'id', label: 'Cluster ID', terraformAttribute: 'id' },
    { key: 'arn', label: 'ARN', terraformAttribute: 'arn' },
    { key: 'endpoint', label: 'Endpoint', terraformAttribute: 'endpoint' },
    { key: 'cluster_security_group_id', label: 'Cluster Security Group ID', terraformAttribute: 'vpc_config[0].cluster_security_group_id' },
  ],

  costEstimation: {
    serviceName: 'EKS',
    staticMonthlyCost: 73,
  },
};
