import type { ResourceSchema } from '@terrastudio/types';

export const securityGroupSchema: ResourceSchema = {
  typeId: 'aws/compute/security_group',
  provider: 'aws',
  displayName: 'Security Group',
  category: 'aws-security',
  description: 'AWS Security Group for controlling inbound and outbound traffic',
  terraformType: 'aws_security_group',
  supportsTags: true,
  requiresResourceGroup: false,
  canBeChildOf: ['aws/networking/vpc'],
  parentReference: { propertyKey: 'vpc_id' },

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'web-sg',
      group: 'General',
      order: 1,
    },
    {
      key: 'description',
      label: 'Description',
      type: 'string',
      required: false,
      defaultValue: 'Managed by TerraStudio',
      placeholder: 'Managed by TerraStudio',
      group: 'General',
      order: 2,
    },
    {
      key: 'ingress_rules',
      label: 'Ingress Rules',
      type: 'array',
      required: false,
      group: 'Ingress',
      order: 3,
      itemSchema: {
        key: 'ingress_rule',
        label: 'Ingress Rule',
        type: 'object',
        required: false,
        nestedSchema: [
          {
            key: 'description',
            label: 'Description',
            type: 'string',
            required: false,
            placeholder: 'Allow HTTP',
          },
          {
            key: 'from_port',
            label: 'From Port',
            type: 'number',
            required: true,
            defaultValue: 80,
          },
          {
            key: 'to_port',
            label: 'To Port',
            type: 'number',
            required: true,
            defaultValue: 80,
          },
          {
            key: 'protocol',
            label: 'Protocol',
            type: 'select',
            required: true,
            defaultValue: 'tcp',
            options: [
              { label: 'TCP', value: 'tcp' },
              { label: 'UDP', value: 'udp' },
              { label: 'ICMP', value: 'icmp' },
              { label: 'All', value: '-1' },
            ],
          },
          {
            key: 'cidr_blocks',
            label: 'CIDR Blocks',
            type: 'array',
            required: false,
            defaultValue: ['0.0.0.0/0'],
            itemSchema: {
              key: 'cidr',
              label: 'CIDR',
              type: 'string',
              required: true,
              placeholder: '0.0.0.0/0',
            },
          },
        ],
      },
    },
    {
      key: 'egress_rules',
      label: 'Egress Rules',
      type: 'array',
      required: false,
      group: 'Egress',
      order: 4,
      defaultValue: [
        {
          description: 'Allow all outbound',
          from_port: 0,
          to_port: 0,
          protocol: '-1',
          cidr_blocks: ['0.0.0.0/0'],
        },
      ],
      itemSchema: {
        key: 'egress_rule',
        label: 'Egress Rule',
        type: 'object',
        required: false,
        nestedSchema: [
          {
            key: 'description',
            label: 'Description',
            type: 'string',
            required: false,
            placeholder: 'Allow all outbound',
          },
          {
            key: 'from_port',
            label: 'From Port',
            type: 'number',
            required: true,
            defaultValue: 0,
          },
          {
            key: 'to_port',
            label: 'To Port',
            type: 'number',
            required: true,
            defaultValue: 0,
          },
          {
            key: 'protocol',
            label: 'Protocol',
            type: 'select',
            required: true,
            defaultValue: '-1',
            options: [
              { label: 'TCP', value: 'tcp' },
              { label: 'UDP', value: 'udp' },
              { label: 'ICMP', value: 'icmp' },
              { label: 'All', value: '-1' },
            ],
          },
          {
            key: 'cidr_blocks',
            label: 'CIDR Blocks',
            type: 'array',
            required: false,
            defaultValue: ['0.0.0.0/0'],
            itemSchema: {
              key: 'cidr',
              label: 'CIDR',
              type: 'string',
              required: true,
              placeholder: '0.0.0.0/0',
            },
          },
        ],
      },
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'Security Group ID', terraformAttribute: 'id' },
    { key: 'arn', label: 'ARN', terraformAttribute: 'arn' },
    { key: 'name', label: 'Name', terraformAttribute: 'name' },
  ],
};
