import type { ResourceSchema } from '@terrastudio/types';

export const vpcSchema: ResourceSchema = {
  typeId: 'aws/networking/vpc',
  provider: 'aws',
  displayName: 'VPC',
  category: 'aws-networking',
  description: 'Amazon Virtual Private Cloud (VPC) for isolating cloud resources',
  terraformType: 'aws_vpc',
  supportsTags: true,
  requiresResourceGroup: false,
  isContainer: true,
  canBeChildOf: [],
  containerStyle: {
    borderColor: '#FF9900',
    borderStyle: 'solid',
    backgroundColor: '#ffffff',
    headerColor: '#232F3E',
    borderRadius: 0,
    borderWidth: 3,
    hideHeaderBorder: true,
    iconSize: 28,
    labelSize: 16,
  },
  minSize: { width: 350, height: 250 },

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'my-vpc',
      group: 'General',
      order: 1,
      validation: {
        minLength: 1,
        maxLength: 255,
      },
    },
    {
      key: 'cidr_block',
      label: 'CIDR Block',
      type: 'cidr',
      required: true,
      description: 'IPv4 CIDR block for the VPC',
      group: 'Networking',
      order: 2,
      defaultValue: '10.0.0.0/16',
    },
    {
      key: 'enable_dns_support',
      label: 'DNS Support',
      type: 'boolean',
      required: false,
      group: 'DNS',
      order: 3,
      defaultValue: true,
      description: 'Enable DNS resolution in the VPC',
    },
    {
      key: 'enable_dns_hostnames',
      label: 'DNS Hostnames',
      type: 'boolean',
      required: false,
      group: 'DNS',
      order: 4,
      defaultValue: false,
      description: 'Enable DNS hostnames in the VPC',
    },
    {
      key: 'instance_tenancy',
      label: 'Instance Tenancy',
      type: 'select',
      required: false,
      group: 'Advanced',
      order: 5,
      defaultValue: 'default',
      description: 'Tenancy of instances launched into the VPC',
      options: [
        { label: 'Default', value: 'default' },
        { label: 'Dedicated', value: 'dedicated' },
      ],
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'VPC ID', terraformAttribute: 'id' },
    { key: 'arn', label: 'ARN', terraformAttribute: 'arn' },
    { key: 'cidr_block', label: 'CIDR Block', terraformAttribute: 'cidr_block' },
    { key: 'default_security_group_id', label: 'Default Security Group ID', terraformAttribute: 'default_security_group_id' },
  ],
};
