import type { ResourceSchema } from '@terrastudio/types';

export const appServicePlanSchema: ResourceSchema = {
  typeId: 'azurerm/compute/app_service_plan',
  provider: 'azurerm',
  displayName: 'App Service Plan',
  category: 'compute',
  description: 'Azure App Service Plan — hosting environment for web apps',
  terraformType: 'azurerm_service_plan',
  supportsTags: true,
  requiresResourceGroup: true,
  cafAbbreviation: 'asp',
  namingConstraints: { maxLength: 60 },
  isContainer: true,
  canBeChildOf: [
    'azurerm/core/resource_group',
  ],
  containerStyle: {
    borderColor: '#2B7CF6',
    borderStyle: 'dotted',
    backgroundColor: '#ffffff',
    headerColor: '#1a1a2e',
    borderRadius: 12,
    borderWidth: 3,
    hideHeaderBorder: true,
    iconSize: 28,
    labelSize: 16,
    dashArray: '4,8',
  },

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'asp-myapp-dev',
      group: 'General',
      order: 1,
      validation: {
        minLength: 1,
        maxLength: 60,
        pattern: '^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]$',
        patternMessage: 'Alphanumerics and hyphens, must start and end with alphanumeric',
      },
    },
    {
      key: 'os_type',
      label: 'OS Type',
      type: 'select',
      required: true,
      group: 'General',
      order: 2,
      defaultValue: 'Linux',
      options: [
        { label: 'Linux', value: 'Linux' },
        { label: 'Windows', value: 'Windows' },
      ],
    },
    {
      key: 'sku_name',
      label: 'SKU',
      type: 'select',
      required: true,
      group: 'General',
      order: 3,
      defaultValue: 'B1',
      options: [
        { label: 'Y1 (Consumption)', value: 'Y1' },
        { label: 'F1 (Free)', value: 'F1' },
        { label: 'B1 (Basic)', value: 'B1' },
        { label: 'B2 (Basic)', value: 'B2' },
        { label: 'B3 (Basic)', value: 'B3' },
        { label: 'S1 (Standard)', value: 'S1' },
        { label: 'S2 (Standard)', value: 'S2' },
        { label: 'S3 (Standard)', value: 'S3' },
        { label: 'P1v3 (Premium v3)', value: 'P1v3' },
        { label: 'P2v3 (Premium v3)', value: 'P2v3' },
        { label: 'P3v3 (Premium v3)', value: 'P3v3' },
      ],
    },
    {
      key: 'worker_count',
      label: 'Instance Count',
      type: 'number',
      required: false,
      group: 'Scaling',
      order: 10,
      defaultValue: 1,
      description: 'Number of worker instances. Set to 3+ for zone redundancy (requires Premium V3 SKU)',
      validation: { min: 1, max: 30 },
    },
    {
      key: 'zone_balancing_enabled',
      label: 'Zone Redundancy',
      type: 'boolean',
      required: false,
      group: 'Scaling',
      order: 11,
      defaultValue: false,
      description: 'Distribute instances across availability zones (requires Premium V3 SKU and worker_count >= 3)',
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
  ],
};
