import type { ResourceSchema } from '@terrastudio/types';

export const diagnosticSettingSchema: ResourceSchema = {
  typeId: 'azurerm/monitoring/diagnostic_setting',
  provider: 'azurerm',
  displayName: 'Diagnostic Setting',
  category: 'monitoring',
  description: 'Routes resource logs and metrics to Log Analytics, Storage Account, or Event Hub',
  terraformType: 'azurerm_monitor_diagnostic_setting',
  supportsTags: false,
  requiresResourceGroup: false,

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'diag',
      group: 'General',
      order: 1,
    },
    {
      key: 'target_resource_id',
      label: 'Target Resource',
      type: 'reference',
      required: true,
      group: 'General',
      order: 2,
      description: 'The resource to collect diagnostics from',
      referenceTargetTypes: [
        'azurerm/compute/app_service',
        'azurerm/compute/function_app',
        'azurerm/compute/app_service_plan',
        'azurerm/compute/virtual_machine',
        'azurerm/containers/container_registry',
        'azurerm/containers/kubernetes_cluster',
        'azurerm/storage/storage_account',
        'azurerm/security/key_vault',
        'azurerm/database/mssql_server',
        'azurerm/database/mssql_database',
        'azurerm/database/mssql_managed_instance',
        'azurerm/database/postgresql_flexible_server',
        'azurerm/database/cosmosdb_account',
        'azurerm/database/redis_cache',
        'azurerm/messaging/servicebus_namespace',
        'azurerm/messaging/eventhub_namespace',
        'azurerm/integration/app_configuration',
        'azurerm/integration/api_management',
        'azurerm/networking/application_gateway',
        'azurerm/networking/firewall',
        'azurerm/networking/bastion_host',
      ],
    },
    {
      key: 'destination_type',
      label: 'Destination',
      type: 'select',
      required: true,
      group: 'Destination',
      order: 10,
      defaultValue: 'log_analytics_workspace',
      options: [
        { label: 'Log Analytics Workspace', value: 'log_analytics_workspace' },
        { label: 'Storage Account', value: 'storage_account' },
        { label: 'Event Hub', value: 'eventhub' },
      ],
    },
    {
      key: 'log_analytics_workspace_id',
      label: 'Log Analytics Workspace',
      type: 'reference',
      required: false,
      group: 'Destination',
      order: 11,
      visibleWhen: { field: 'destination_type', operator: 'eq', value: 'log_analytics_workspace' },
      referenceTargetTypes: ['azurerm/monitoring/log_analytics_workspace'],
    },
    {
      key: 'log_analytics_destination_type',
      label: 'Log Destination Type',
      type: 'select',
      required: false,
      group: 'Destination',
      order: 12,
      visibleWhen: { field: 'destination_type', operator: 'eq', value: 'log_analytics_workspace' },
      defaultValue: 'AzureDiagnostics',
      options: [
        { label: 'Azure Diagnostics (legacy schema)', value: 'AzureDiagnostics' },
        { label: 'Dedicated (resource-specific tables)', value: 'Dedicated' },
      ],
    },
    {
      key: 'storage_account_id',
      label: 'Storage Account',
      type: 'reference',
      required: false,
      group: 'Destination',
      order: 13,
      visibleWhen: { field: 'destination_type', operator: 'eq', value: 'storage_account' },
      referenceTargetTypes: ['azurerm/storage/storage_account'],
    },
    {
      key: 'eventhub_authorization_rule_id',
      label: 'Event Hub Auth Rule ID',
      type: 'string',
      required: false,
      group: 'Destination',
      order: 14,
      visibleWhen: { field: 'destination_type', operator: 'eq', value: 'eventhub' },
      description: 'Full Terraform reference or ARM ID of the Event Hub authorization rule',
    },
    {
      key: 'eventhub_name',
      label: 'Event Hub Name',
      type: 'string',
      required: false,
      group: 'Destination',
      order: 15,
      visibleWhen: { field: 'destination_type', operator: 'eq', value: 'eventhub' },
    },
    {
      key: 'enabled_log_categories',
      label: 'Log Category Groups',
      type: 'multiselect',
      required: false,
      group: 'Collection',
      order: 20,
      defaultValue: ['allLogs'],
      description: 'Use category groups (allLogs / audit) or leave empty and use per-category',
      options: [
        { label: 'All logs', value: 'allLogs' },
        { label: 'Audit only', value: 'audit' },
      ],
    },
    {
      key: 'enabled_metrics',
      label: 'Metric Categories',
      type: 'array',
      required: false,
      group: 'Collection',
      order: 21,
      description: 'Metric category names to enable (e.g. AllMetrics)',
      itemSchema: {
        key: 'metric',
        label: 'Metric Category',
        type: 'string',
        required: true,
        placeholder: 'AllMetrics',
      },
      defaultValue: ['AllMetrics'],
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
  ],

  costEstimation: { serviceName: 'Diagnostic Setting', staticMonthlyCost: 0 },
};
