import type { ResourceSchema } from '@terrastudio/types';

export const lambdaFunctionSchema: ResourceSchema = {
  typeId: 'aws/compute/lambda_function',
  provider: 'aws',
  displayName: 'Lambda Function',
  category: 'aws-compute',
  description: 'AWS Lambda serverless function',
  terraformType: 'aws_lambda_function',
  supportsTags: true,
  requiresResourceGroup: false,

  properties: [
    {
      key: 'name',
      label: 'Function Name',
      type: 'string',
      required: true,
      placeholder: 'my-handler',
      group: 'General',
      order: 1,
      validation: { maxLength: 64 },
    },
    {
      key: 'runtime',
      label: 'Runtime',
      type: 'select',
      required: true,
      defaultValue: 'nodejs20.x',
      group: 'General',
      order: 2,
      options: [
        { label: 'Node.js 20.x', value: 'nodejs20.x' },
        { label: 'Node.js 18.x', value: 'nodejs18.x' },
        { label: 'Python 3.12', value: 'python3.12' },
        { label: 'Python 3.11', value: 'python3.11' },
        { label: 'Java 21', value: 'java21' },
        { label: 'Java 17', value: 'java17' },
        { label: 'Go 1.x', value: 'provided.al2023' },
        { label: '.NET 8', value: 'dotnet8' },
        { label: 'Ruby 3.3', value: 'ruby3.3' },
      ],
    },
    {
      key: 'handler',
      label: 'Handler',
      type: 'string',
      required: true,
      defaultValue: 'index.handler',
      placeholder: 'index.handler',
      group: 'General',
      order: 3,
    },
    {
      key: 'memory_size',
      label: 'Memory (MB)',
      type: 'select',
      required: false,
      defaultValue: '128',
      group: 'Configuration',
      order: 4,
      options: [
        { label: '128 MB', value: '128' },
        { label: '256 MB', value: '256' },
        { label: '512 MB', value: '512' },
        { label: '1024 MB', value: '1024' },
        { label: '2048 MB', value: '2048' },
        { label: '3008 MB', value: '3008' },
      ],
    },
    {
      key: 'timeout',
      label: 'Timeout (seconds)',
      type: 'number',
      required: false,
      defaultValue: 30,
      group: 'Configuration',
      order: 5,
      validation: { min: 1, max: 900 },
    },
    {
      key: 'description',
      label: 'Description',
      type: 'string',
      required: false,
      placeholder: 'Processes incoming API requests',
      group: 'General',
      order: 6,
    },
    {
      key: 'deployment_source',
      label: 'Deployment Source',
      type: 'select',
      required: true,
      defaultValue: 'local_file',
      group: 'Deployment',
      order: 7,
      options: [
        { label: 'Local File', value: 'local_file' },
        { label: 'S3', value: 's3' },
      ],
    },
    {
      key: 'filename',
      label: 'Filename',
      type: 'string',
      required: false,
      defaultValue: 'lambda.zip',
      placeholder: 'path/to/package.zip',
      group: 'Deployment',
      order: 8,
      visibleWhen: { field: 'deployment_source', operator: 'eq', value: 'local_file' },
    },
    {
      key: 's3_bucket',
      label: 'S3 Bucket',
      type: 'string',
      required: false,
      placeholder: 'my-deployment-bucket',
      group: 'Deployment',
      order: 9,
      visibleWhen: { field: 'deployment_source', operator: 'eq', value: 's3' },
    },
    {
      key: 's3_key',
      label: 'S3 Key',
      type: 'string',
      required: false,
      placeholder: 'lambdas/my-function.zip',
      group: 'Deployment',
      order: 10,
      visibleWhen: { field: 'deployment_source', operator: 'eq', value: 's3' },
    },
    {
      key: 'environment_variables',
      label: 'Environment Variables',
      type: 'key-value-map',
      required: false,
      group: 'Environment',
      order: 11,
    },
    {
      key: 'role_enabled',
      label: 'IAM Role',
      type: 'boolean',
      required: false,
      defaultValue: false,
      description: 'Assign an IAM execution role',
      group: 'Security',
      order: 12,
    },
    {
      key: 'role_arn',
      label: 'IAM Role',
      type: 'reference',
      required: false,
      referenceTargetTypes: ['aws/security/iam_role'],
      group: 'Security',
      order: 13,
      visibleWhen: { field: 'role_enabled', operator: 'truthy' },
    },
  ],

  handles: [
    { id: 'lambda-trigger', type: 'target', position: 'left', label: 'Trigger', acceptsTypes: ['aws/compute/api_gateway'] },
    { id: 'lambda-out', type: 'source', position: 'right', label: 'Lambda' },
  ],

  outputs: [
    { key: 'arn', label: 'ARN', terraformAttribute: 'arn' },
    { key: 'invoke_arn', label: 'Invoke ARN', terraformAttribute: 'invoke_arn' },
    { key: 'function_name', label: 'Function Name', terraformAttribute: 'function_name' },
    { key: 'qualified_arn', label: 'Qualified ARN', terraformAttribute: 'qualified_arn' },
  ],

  costEstimation: {
    serviceName: 'Lambda',
    usageInputs: [
      {
        key: '_cost_requests_millions',
        label: 'Monthly Requests',
        unit: 'million',
        defaultValue: 1,
        min: 0,
        max: 100000,
        description: 'Monthly invocation count (~$0.20/million after free tier)',
      },
      {
        key: '_cost_duration_ms',
        label: 'Avg Duration',
        unit: 'ms',
        defaultValue: 200,
        min: 1,
        max: 900000,
        description: 'Average execution duration per invocation',
      },
    ],
  },
};
