import type { ResourceSchema } from '@terrastudio/types';

export const availabilitySetSchema: ResourceSchema = {
  typeId: 'azurerm/compute/availability_set',
  provider: 'azurerm',
  displayName: 'Availability Set',
  category: 'compute',
  description: 'Azure Availability Set for VM high availability',
  terraformType: 'azurerm_availability_set',
  supportsTags: true,
  requiresResourceGroup: true,
  cafAbbreviation: 'avail',
  canBeChildOf: ['azurerm/core/resource_group'],
  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'avail-web-dev',
      group: 'General',
      order: 1,
      validation: {
        minLength: 1,
        maxLength: 80,
        pattern: '^[a-zA-Z0-9][a-zA-Z0-9_.-]*[a-zA-Z0-9_]$',
        patternMessage: 'Alphanumerics, hyphens, underscores, dots',
      },
    },
    {
      key: 'platform_fault_domain_count',
      label: 'Fault Domain Count',
      type: 'select',
      required: false,
      group: 'Configuration',
      order: 2,
      defaultValue: '2',
      description: 'Number of fault domains (1-3)',
      options: [
        { label: '1', value: '1' },
        { label: '2', value: '2' },
        { label: '3', value: '3' },
      ],
    },
    {
      key: 'platform_update_domain_count',
      label: 'Update Domain Count',
      type: 'select',
      required: false,
      group: 'Configuration',
      order: 3,
      defaultValue: '5',
      description: 'Number of update domains (1-20)',
      options: [
        { label: '1', value: '1' },
        { label: '2', value: '2' },
        { label: '3', value: '3' },
        { label: '5', value: '5' },
        { label: '10', value: '10' },
        { label: '15', value: '15' },
        { label: '20', value: '20' },
      ],
    },
    {
      key: 'managed',
      label: 'Managed Disks',
      type: 'boolean',
      required: false,
      group: 'Configuration',
      order: 4,
      defaultValue: true,
      description: 'Use managed disks for VMs in this availability set',
    },
  ],
  handles: [
    { id: 'avset-out', type: 'source', position: 'bottom', label: 'Availability Set' },
  ],
  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
  ],
};
