import type { ResourceSchema } from '@terrastudio/types';

export const applicationGatewaySchema: ResourceSchema = {
  typeId: 'azurerm/networking/application_gateway',
  provider: 'azurerm',
  displayName: 'Application Gateway',
  category: 'networking',
  description: 'Azure Application Gateway — web traffic load balancer with URL-based routing, SSL termination, and WAF',
  terraformType: 'azurerm_application_gateway',
  supportsTags: true,
  requiresResourceGroup: true,
  cafAbbreviation: 'agw',
  namingConstraints: { maxLength: 80 },

  canBeChildOf: [
    'azurerm/core/resource_group',
    'azurerm/networking/subnet',
  ],

  parentReference: { propertyKey: 'subnet_id' },

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'agw-myapp-dev',
      group: 'General',
      order: 1,
      validation: {
        minLength: 1,
        maxLength: 80,
        pattern: '^[a-zA-Z0-9][a-zA-Z0-9_.-]*[a-zA-Z0-9_]$',
        patternMessage: 'Must start with alphanumeric, end with alphanumeric or underscore',
      },
    },
    {
      key: 'http2_enabled',
      label: 'HTTP/2',
      type: 'boolean',
      required: false,
      group: 'General',
      order: 1.5,
      defaultValue: false,
      description: 'Enable HTTP/2 support',
    },
    {
      key: 'zones',
      label: 'Availability Zones',
      type: 'array',
      required: false,
      group: 'General',
      order: 1.6,
      description: 'Availability zones for the Application Gateway',
      itemSchema: { key: 'zone', label: 'Zone', type: 'string', required: true },
    },
    {
      key: 'sku_name',
      label: 'SKU Name',
      type: 'select',
      required: true,
      group: 'General',
      order: 2,
      defaultValue: 'Standard_v2',
      options: [
        { label: 'Standard v2', value: 'Standard_v2' },
        { label: 'WAF v2', value: 'WAF_v2' },
      ],
    },
    {
      key: 'sku_tier',
      label: 'SKU Tier',
      type: 'select',
      required: true,
      group: 'General',
      order: 3,
      defaultValue: 'Standard_v2',
      options: [
        { label: 'Standard v2', value: 'Standard_v2' },
        { label: 'WAF v2', value: 'WAF_v2' },
      ],
    },
    {
      key: 'capacity',
      label: 'Fixed Capacity',
      type: 'number',
      required: false,
      group: 'Scaling',
      order: 10,
      defaultValue: 2,
      description: 'Fixed instance count (ignored when autoscale is configured)',
      validation: { min: 1, max: 125 },
    },
    {
      key: 'autoscale_min',
      label: 'Autoscale Min Capacity',
      type: 'number',
      required: false,
      group: 'Scaling',
      order: 11,
      description: 'Minimum capacity for autoscale (set to enable autoscale instead of fixed capacity)',
      validation: { min: 0, max: 100 },
    },
    {
      key: 'autoscale_max',
      label: 'Autoscale Max Capacity',
      type: 'number',
      required: false,
      group: 'Scaling',
      order: 12,
      description: 'Maximum capacity for autoscale',
      validation: { min: 2, max: 125 },
    },
    {
      key: 'frontend_port',
      label: 'Frontend Port',
      type: 'number',
      required: true,
      group: 'Frontend',
      order: 20,
      defaultValue: 80,
      description: 'Listener port for incoming traffic',
      validation: { min: 1, max: 65535 },
    },
    {
      key: 'backend_fqdns',
      label: 'Backend FQDNs',
      type: 'array',
      required: false,
      group: 'Backend',
      order: 30,
      description: 'Fully qualified domain names for the backend pool',
    },
    {
      key: 'backend_port',
      label: 'Backend Port',
      type: 'number',
      required: true,
      group: 'Backend',
      order: 31,
      defaultValue: 80,
      description: 'Port for backend HTTP settings',
      validation: { min: 1, max: 65535 },
    },
    {
      key: 'backend_protocol',
      label: 'Backend Protocol',
      type: 'select',
      required: true,
      group: 'Backend',
      order: 32,
      defaultValue: 'Http',
      options: [
        { label: 'HTTP', value: 'Http' },
        { label: 'HTTPS', value: 'Https' },
      ],
    },
    {
      key: 'cookie_based_affinity',
      label: 'Cookie-Based Affinity',
      type: 'select',
      required: false,
      group: 'Backend',
      order: 33,
      defaultValue: 'Disabled',
      options: [
        { label: 'Disabled', value: 'Disabled' },
        { label: 'Enabled', value: 'Enabled' },
      ],
    },
    {
      key: 'request_timeout',
      label: 'Request Timeout (seconds)',
      type: 'number',
      required: false,
      group: 'Backend',
      order: 34,
      defaultValue: 60,
      description: 'Backend request timeout in seconds',
      validation: { min: 1, max: 86400 },
    },
    {
      key: 'waf_enabled',
      label: 'WAF Enabled',
      type: 'boolean',
      required: false,
      group: 'WAF',
      order: 40,
      defaultValue: false,
      description: 'Enable Web Application Firewall (requires WAF_v2 SKU)',
      visibleWhen: { field: 'sku_name', operator: 'eq', value: 'WAF_v2' },
    },
    {
      key: 'waf_mode',
      label: 'WAF Mode',
      type: 'select',
      required: false,
      group: 'WAF',
      order: 41,
      defaultValue: 'Detection',
      options: [
        { label: 'Detection', value: 'Detection' },
        { label: 'Prevention', value: 'Prevention' },
      ],
      description: 'Detection mode logs threats; Prevention mode blocks them',
      visibleWhen: { field: 'waf_enabled', operator: 'eq', value: true },
    },
    {
      key: 'waf_rule_set_version',
      label: 'WAF Rule Set Version',
      type: 'select',
      required: false,
      group: 'WAF',
      order: 42,
      defaultValue: '3.2',
      options: [
        { label: 'OWASP 3.2', value: '3.2' },
        { label: 'OWASP 3.1', value: '3.1' },
        { label: 'OWASP 3.0', value: '3.0' },
      ],
      visibleWhen: { field: 'waf_enabled', operator: 'eq', value: true },
    },
    {
      key: 'subnet_id',
      label: 'Subnet',
      type: 'reference',
      required: false,
      group: 'Network',
      order: 50,
      referenceTargetTypes: ['azurerm/networking/subnet'],
      description: 'Dedicated subnet for Application Gateway (at least /24 recommended)',
    },
    {
      key: 'pip_id',
      label: 'Public IP',
      type: 'reference',
      required: false,
      group: 'Network',
      order: 51,
      referenceTargetTypes: ['azurerm/networking/public_ip'],
      description: 'Standard SKU Public IP (Static allocation required for v2)',
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'backend_address_pool_id', label: 'Backend Pool ID', terraformAttribute: 'backend_address_pool.0.id' },
    { key: 'frontend_ip_configuration_id', label: 'Frontend IP Config ID', terraformAttribute: 'frontend_ip_configuration.0.id' },
  ],

  costEstimation: {
    serviceName: 'Application Gateway',
    skuProperty: 'sku_name',
    usageInputs: [
      {
        key: '_cost_capacity_units',
        label: 'Capacity Units',
        unit: 'CU-hours/mo',
        defaultValue: 744,
        min: 0,
        max: 1000000,
        description: 'v2 SKU charges per capacity unit-hour. Each unit includes compute, connections, and throughput.',
      },
    ],
  },
};
