import type { ResourceSchema } from '@terrastudio/types';

export const dnsCnameRecordSchema: ResourceSchema = {
	typeId: 'azurerm/dns/dns_cname_record',
	provider: 'azurerm',
	displayName: 'DNS CNAME Record',
	category: 'dns',
	description: 'DNS CNAME record mapping a hostname to another hostname',
	terraformType: 'azurerm_dns_cname_record',
	supportsTags: true,
	requiresResourceGroup: true,
	cafAbbreviation: 'dnsc',
	canBeChildOf: ['azurerm/dns/dns_zone'],
	parentReference: { propertyKey: 'dns_zone_id' },
	properties: [
		{
			key: 'name',
			label: 'Record Name',
			type: 'string',
			required: true,
			placeholder: 'www',
			group: 'General',
			order: 1,
			description: 'Subdomain name (e.g. "www", "api")',
			validation: { minLength: 1, maxLength: 80 },
		},
		{
			key: 'ttl',
			label: 'TTL (seconds)',
			type: 'number',
			required: false,
			group: 'General',
			order: 2,
			defaultValue: 3600,
			validation: { min: 1, max: 2147483647 },
		},
		{
			key: 'record_mode',
			label: 'Record Mode',
			type: 'select',
			required: true,
			group: 'Record',
			order: 4,
			defaultValue: 'cname',
			options: [
				{ label: 'Target FQDN', value: 'cname' },
				{ label: 'Target Resource (alias)', value: 'alias' },
			],
		},
		{
			key: 'record',
			label: 'Target FQDN',
			type: 'string',
			required: false,
			group: 'Record',
			order: 5,
			placeholder: 'myapp.azurewebsites.net',
			description: 'Fully qualified domain name to point to',
			visibleWhen: { field: 'record_mode', operator: 'eq', value: 'cname' },
		},
		{
			key: 'target_resource_id',
			label: 'Target Resource',
			type: 'reference',
			required: false,
			group: 'Record',
			order: 6,
			description: 'Azure resource to alias (App Service, Static Web App, CDN Endpoint)',
			referenceTargetTypes: [
				'azurerm/compute/app_service',
				'azurerm/web/static_web_app',
				'azurerm/web/cdn_endpoint',
			],
			visibleWhen: { field: 'record_mode', operator: 'eq', value: 'alias' },
			showAsEdge: true,
		},
	],
	handles: [],
	outputs: [
		{ key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
		{ key: 'fqdn', label: 'FQDN', terraformAttribute: 'fqdn' },
	],
};
