import type { ResourceSchema } from '@terrastudio/types';

export const cognitiveAccountSchema: ResourceSchema = {
  typeId: 'azurerm/ai/cognitive_account',
  provider: 'azurerm',
  displayName: 'Cognitive Account',
  category: 'ai',
  description: 'Azure Cognitive Services account for AI capabilities like OpenAI, Vision, Speech, and Language',
  terraformType: 'azurerm_cognitive_account',
  supportsTags: true,
  requiresResourceGroup: true,
  cafAbbreviation: 'cog',
  canBeChildOf: ['azurerm/core/resource_group'],

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'my-cognitive-account',
      group: 'General',
      order: 1,
    },
    {
      key: 'kind',
      label: 'Kind',
      type: 'select',
      required: true,
      group: 'General',
      order: 2,
      defaultValue: 'OpenAI',
      options: [
        { label: 'OpenAI', value: 'OpenAI' },
        { label: 'Cognitive Services', value: 'CognitiveServices' },
        { label: 'AI Services', value: 'AIServices' },
        { label: 'Computer Vision', value: 'ComputerVision' },
        { label: 'Face', value: 'Face' },
        { label: 'Text Analytics', value: 'TextAnalytics' },
        { label: 'Speech Services', value: 'SpeechServices' },
        { label: 'Content Safety', value: 'ContentSafety' },
        { label: 'Form Recognizer', value: 'FormRecognizer' },
      ],
    },
    {
      key: 'sku_name',
      label: 'SKU',
      type: 'select',
      required: true,
      group: 'General',
      order: 3,
      defaultValue: 'S0',
      options: [
        { label: 'F0 (Free)', value: 'F0' },
        { label: 'S0 (Standard)', value: 'S0' },
        { label: 'S1 (Standard S1)', value: 'S1' },
      ],
    },
    {
      key: 'custom_subdomain_name',
      label: 'Custom Subdomain Name',
      type: 'string',
      required: false,
      placeholder: 'my-cognitive-subdomain',
      group: 'General',
      order: 4,
      description: 'Custom subdomain for the Cognitive Services endpoint',
    },
    {
      key: 'public_network_access_enabled',
      label: 'Public Network Access',
      type: 'boolean',
      required: false,
      group: 'Security',
      order: 5,
      defaultValue: true,
    },
    {
      key: 'local_auth_enabled',
      label: 'Local Authentication',
      type: 'boolean',
      required: false,
      group: 'Security',
      order: 6,
      defaultValue: true,
      description: 'Enable authentication using API keys',
    },
  ],

  handles: [
    {
      id: 'cognitive-out',
      type: 'source',
      position: 'right',
      label: 'Cognitive Services',
    },
  ],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'endpoint', label: 'API Endpoint', terraformAttribute: 'endpoint' },
    {
      key: 'primary_access_key',
      label: 'Primary Access Key',
      terraformAttribute: 'primary_access_key',
      sensitive: true,
    },
    {
      key: 'secondary_access_key',
      label: 'Secondary Access Key',
      terraformAttribute: 'secondary_access_key',
      sensitive: true,
    },
  ],
};
