import type { Template } from '../types';

export const secureWebAppTemplate: Template = {
  templateVersion: 1,
  metadata: {
    id: 'secure-web-app',
    name: 'Secure Web App',
    description: 'App Service + SQL Database + Key Vault with monitoring',
    categories: ['Web Applications', 'Security'],
    icon: 'security',
  },
  diagram: {
    nodes: [
      {
        id: 'tmpl-sub',
        type: 'azurerm/core/subscription',
        position: { x: 50, y: 50 },
        data: {
          typeId: 'azurerm/core/subscription',
          properties: {},
          references: {},
          terraformName: 'sub_1',
          label: 'Subscription',
          validationErrors: [],
          enabledOutputs: [],
        },
        width: 1350,
        height: 850,
        style: 'width: 1350px; height: 850px;',
      },
      {
        id: 'tmpl-rg',
        type: 'azurerm/core/resource_group',
        position: { x: 50, y: 60 },
        parentId: 'tmpl-sub',
        data: {
          typeId: 'azurerm/core/resource_group',
          properties: { location: 'eastus' },
          references: {},
          terraformName: 'rg_1',
          label: 'Resource Group',
          validationErrors: [],
          enabledOutputs: [],
        },
        width: 1250,
        height: 750,
        style: 'width: 1250px; height: 750px;',
      },
      // App Service Plan
      {
        id: 'tmpl-plan',
        type: 'azurerm/compute/app_service_plan',
        position: { x: 30, y: 60 },
        parentId: 'tmpl-rg',
        data: {
          typeId: 'azurerm/compute/app_service_plan',
          properties: {
            name: 'webapp',
            os_type: 'Linux',
            sku_name: 'B1',
          },
          references: {},
          terraformName: 'asp_1',
          label: 'App Service Plan',
          validationErrors: [],
          enabledOutputs: [],
        },
        width: 350,
        height: 250,
        style: 'width: 350px; height: 250px;',
      },
      // App Service inside plan
      {
        id: 'tmpl-app',
        type: 'azurerm/compute/app_service',
        position: { x: 30, y: 60 },
        parentId: 'tmpl-plan',
        data: {
          typeId: 'azurerm/compute/app_service',
          properties: {
            name: 'webapp',
            os_type: 'linux',
            runtime_stack: 'NODE|18-lts',
            https_only: true,
            always_on: false,
          },
          references: {},
          terraformName: 'app_1',
          label: 'Web App',
          validationErrors: [],
          enabledOutputs: [],
        },
      },
      // SQL Server
      {
        id: 'tmpl-sql-server',
        type: 'azurerm/database/mssql_server',
        position: { x: 450, y: 60 },
        parentId: 'tmpl-rg',
        data: {
          typeId: 'azurerm/database/mssql_server',
          properties: {
            name: 'sqlserver',
            version: '12.0',
            administrator_login: 'sqladmin',
            administrator_login_password: '',
            minimum_tls_version: '1.2',
            public_network_access_enabled: true,
          },
          references: {},
          terraformName: 'sql_1',
          label: 'SQL Server',
          validationErrors: [],
          enabledOutputs: ['fully_qualified_domain_name'],
        },
        width: 350,
        height: 250,
        style: 'width: 350px; height: 250px;',
      },
      // SQL Database inside server
      {
        id: 'tmpl-sql-db',
        type: 'azurerm/database/mssql_database',
        position: { x: 30, y: 60 },
        parentId: 'tmpl-sql-server',
        data: {
          typeId: 'azurerm/database/mssql_database',
          properties: {
            name: 'appdb',
            sku_name: 'S0',
            collation: 'SQL_Latin1_General_CP1_CI_AS',
            max_size_gb: 2,
          },
          references: {},
          terraformName: 'sqldb_1',
          label: 'App Database',
          validationErrors: [],
          enabledOutputs: [],
        },
      },
      // Key Vault
      {
        id: 'tmpl-kv',
        type: 'azurerm/security/key_vault',
        position: { x: 870, y: 60 },
        parentId: 'tmpl-rg',
        data: {
          typeId: 'azurerm/security/key_vault',
          properties: {
            name: 'webapp',
            sku_name: 'standard',
            soft_delete_retention_days: 90,
            purge_protection_enabled: false,
          },
          references: {},
          terraformName: 'kv_1',
          label: 'Key Vault',
          validationErrors: [],
          enabledOutputs: [],
        },
      },
      // Application Insights
      {
        id: 'tmpl-appinsights',
        type: 'azurerm/monitoring/application_insights',
        position: { x: 30, y: 380 },
        parentId: 'tmpl-rg',
        data: {
          typeId: 'azurerm/monitoring/application_insights',
          properties: {
            name: 'appi-webapp',
            application_type: 'web',
            retention_in_days: 90,
            sampling_percentage: 100,
          },
          references: {
            workspace_id: 'tmpl-law',
          },
          terraformName: 'appi_1',
          label: 'Application Insights',
          validationErrors: [],
          enabledOutputs: [],
        },
      },
      // Log Analytics Workspace
      {
        id: 'tmpl-law',
        type: 'azurerm/monitoring/log_analytics_workspace',
        position: { x: 300, y: 380 },
        parentId: 'tmpl-rg',
        data: {
          typeId: 'azurerm/monitoring/log_analytics_workspace',
          properties: {
            name: 'law-webapp',
            sku: 'PerGB2018',
            retention_in_days: 30,
          },
          references: {},
          terraformName: 'law_1',
          label: 'Log Analytics',
          validationErrors: [],
          enabledOutputs: [],
        },
      },
    ],
    edges: [
      {
        id: 'tmpl-edge-sql-kv',
        source: 'tmpl-sql-server',
        target: 'tmpl-kv',
        sourceHandle: 'out-fully_qualified_domain_name',
        targetHandle: 'secret-in',
      },
    ],
  },
};
