import type { Template } from '../types';

export const serverlessDataApiTemplate: Template = {
  templateVersion: 1,
  metadata: {
    id: 'serverless-data-api',
    name: 'Serverless Data API',
    description:
      'Function App backed by SQL, Blob Storage, and Key Vault for secrets. Includes monitoring with Log Analytics and Application Insights.',
    categories: ['Serverless'],
    icon: 'compute',
  },
  diagram: {
    nodes: [
      // Subscription
      {
        id: 'tmpl-sub',
        type: 'azurerm/core/subscription',
        position: { x: 50, y: 50 },
        data: {
          typeId: 'azurerm/core/subscription',
          properties: {},
          references: {},
          terraformName: 'sub_1',
          label: 'Subscription',
          validationErrors: [],
          enabledOutputs: [],
        },
        width: 1500,
        height: 870,
        style: 'width: 1500px; height: 870px;',
      },
      // Resource Group
      {
        id: 'tmpl-rg',
        type: 'azurerm/core/resource_group',
        position: { x: 50, y: 60 },
        parentId: 'tmpl-sub',
        data: {
          typeId: 'azurerm/core/resource_group',
          properties: { location: 'eastus' },
          references: {},
          terraformName: 'rg_1',
          label: 'Resource Group',
          validationErrors: [],
          enabledOutputs: [],
        },
        width: 1400,
        height: 770,
        style: 'width: 1400px; height: 770px;',
      },
      // ── Consumption Plan + Function App ──────────────────────────────────
      {
        id: 'tmpl-plan',
        type: 'azurerm/compute/app_service_plan',
        position: { x: 30, y: 60 },
        parentId: 'tmpl-rg',
        data: {
          typeId: 'azurerm/compute/app_service_plan',
          properties: {
            name: 'functions',
            os_type: 'Linux',
            sku_name: 'Y1',
          },
          references: {},
          terraformName: 'asp_1',
          label: 'Consumption Plan',
          validationErrors: [],
          enabledOutputs: [],
        },
        width: 380,
        height: 260,
        style: 'width: 380px; height: 260px;',
      },
      {
        id: 'tmpl-func',
        type: 'azurerm/compute/function_app',
        position: { x: 30, y: 60 },
        parentId: 'tmpl-plan',
        data: {
          typeId: 'azurerm/compute/function_app',
          properties: {
            name: 'dataapi',
            os_type: 'linux',
            runtime_stack: 'node',
            runtime_version: '20',
            https_only: true,
          },
          references: { storage_account_id: 'tmpl-storage' },
          terraformName: 'func_1',
          label: 'Data API',
          validationErrors: [],
          enabledOutputs: [],
        },
      },
      // ── Storage Account (required by Functions) ────────────────────────────
      {
        id: 'tmpl-storage',
        type: 'azurerm/storage/storage_account',
        position: { x: 510, y: 60 },
        parentId: 'tmpl-rg',
        data: {
          typeId: 'azurerm/storage/storage_account',
          properties: {
            name: 'dataapist',
            account_tier: 'Standard',
            account_replication_type: 'LRS',
            account_kind: 'StorageV2',
            min_tls_version: 'TLS1_2',
          },
          references: {},
          terraformName: 'st_1',
          label: 'Function Storage',
          validationErrors: [],
          enabledOutputs: ['primary_connection_string'],
        },
        width: 380,
        height: 240,
        style: 'width: 380px; height: 240px;',
      },
      // Blob Container inside storage (for data uploads)
      {
        id: 'tmpl-blob',
        type: 'azurerm/storage/blob_container',
        position: { x: 30, y: 70 },
        parentId: 'tmpl-storage',
        data: {
          typeId: 'azurerm/storage/blob_container',
          properties: { name: 'data', container_access_type: 'private' },
          references: {},
          terraformName: 'blob_data',
          label: 'data',
          validationErrors: [],
          enabledOutputs: [],
        },
      },
      // ── SQL Server + Database ──────────────────────────────────────────────
      {
        id: 'tmpl-sql-server',
        type: 'azurerm/database/mssql_server',
        position: { x: 990, y: 60 },
        parentId: 'tmpl-rg',
        data: {
          typeId: 'azurerm/database/mssql_server',
          properties: {
            name: 'dataapi',
            version: '12.0',
            administrator_login: 'sqladmin',
            administrator_login_password: '',
            minimum_tls_version: '1.2',
            public_network_access_enabled: false,
          },
          references: {},
          terraformName: 'sql_1',
          label: 'SQL Server',
          validationErrors: [],
          enabledOutputs: ['fully_qualified_domain_name'],
        },
        width: 380,
        height: 240,
        style: 'width: 380px; height: 240px;',
      },
      {
        id: 'tmpl-sql-db',
        type: 'azurerm/database/mssql_database',
        position: { x: 30, y: 70 },
        parentId: 'tmpl-sql-server',
        data: {
          typeId: 'azurerm/database/mssql_database',
          properties: {
            name: 'datastore',
            sku_name: 'S1',
            collation: 'SQL_Latin1_General_CP1_CI_AS',
            max_size_gb: 10,
            zone_redundant: false,
          },
          references: {},
          terraformName: 'sqldb_1',
          label: 'Data Store',
          validationErrors: [],
          enabledOutputs: [],
        },
      },
      // ── Key Vault ──────────────────────────────────────────────────────────
      {
        id: 'tmpl-kv',
        type: 'azurerm/security/key_vault',
        position: { x: 30, y: 490 },
        parentId: 'tmpl-rg',
        data: {
          typeId: 'azurerm/security/key_vault',
          properties: {
            name: 'dataapikv',
            sku_name: 'standard',
            soft_delete_retention_days: 90,
            purge_protection_enabled: false,
          },
          references: {},
          terraformName: 'kv_1',
          label: 'Key Vault',
          validationErrors: [],
          enabledOutputs: [],
        },
      },
      // ── Monitoring ─────────────────────────────────────────────────────────
      {
        id: 'tmpl-law',
        type: 'azurerm/monitoring/log_analytics_workspace',
        position: { x: 510, y: 490 },
        parentId: 'tmpl-rg',
        data: {
          typeId: 'azurerm/monitoring/log_analytics_workspace',
          properties: {
            name: 'law',
            sku: 'PerGB2018',
            retention_in_days: 30,
          },
          references: {},
          terraformName: 'law_1',
          label: 'Log Analytics',
          validationErrors: [],
          enabledOutputs: [],
        },
      },
      {
        id: 'tmpl-appi',
        type: 'azurerm/monitoring/application_insights',
        position: { x: 800, y: 490 },
        parentId: 'tmpl-rg',
        data: {
          typeId: 'azurerm/monitoring/application_insights',
          properties: {
            name: 'appi',
            application_type: 'web',
            retention_in_days: 90,
            sampling_percentage: 100,
          },
          references: { workspace_id: 'tmpl-law' },
          terraformName: 'appi_1',
          label: 'Application Insights',
          validationErrors: [],
          enabledOutputs: [],
        },
      },
    ],
    edges: [
      // Storage connection string → Key Vault secret
      {
        id: 'tmpl-edge-0',
        source: 'tmpl-storage',
        target: 'tmpl-kv',
        sourceHandle: 'out-primary_connection_string',
        targetHandle: 'secret-in',
        animated: true,
        label: 'Storage connection string',
      },
      // SQL FQDN → Key Vault secret
      {
        id: 'tmpl-edge-1',
        source: 'tmpl-sql-server',
        target: 'tmpl-kv',
        sourceHandle: 'out-fully_qualified_domain_name',
        targetHandle: 'secret-in',
        animated: true,
        label: 'SQL server hostname',
      },
    ],
  },
};
