import type { ResourceSchema } from '@terrastudio/types';

export const mysqlFlexibleServerSchema: ResourceSchema = {
  typeId: 'azurerm/database/mysql_flexible_server',
  provider: 'azurerm',
  displayName: 'MySQL Flexible Server',
  category: 'mysql',
  description: 'Azure Database for MySQL Flexible Server — fully managed relational database',
  terraformType: 'azurerm_mysql_flexible_server',
  supportsTags: true,
  requiresResourceGroup: true,
  cafAbbreviation: 'mysql',
  namingConstraints: { lowercase: true, maxLength: 63 },
  isContainer: true,

  canBeChildOf: [
    'azurerm/core/resource_group',
    'azurerm/networking/subnet',
  ],
  visualContainment: true,
  privateEndpointConfig: {
    subresources: [
      { key: 'mysqlServer', label: 'MySQL Server' },
    ],
    defaultSubresource: 'mysqlServer',
  },

  containerStyle: {
    borderColor: '#00758F',
    borderStyle: 'dotted',
    backgroundColor: '#ffffff',
    headerColor: '#1a1a2e',
    borderRadius: 12,
    borderWidth: 3,
    hideHeaderBorder: true,
    iconSize: 28,
    labelSize: 16,
    dashArray: '4,8',
  },

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'mysql-myapp-dev',
      group: 'General',
      order: 1,
      validation: {
        minLength: 3,
        maxLength: 63,
        pattern: '^[a-z0-9][a-z0-9-]*[a-z0-9]$',
        patternMessage: 'Lowercase letters, numbers, and hyphens only',
      },
    },
    {
      key: 'version',
      label: 'MySQL Version',
      type: 'select',
      required: true,
      group: 'General',
      order: 2,
      defaultValue: '8.0.21',
      options: [
        { label: '8.0.21 (latest)', value: '8.0.21' },
        { label: '5.7', value: '5.7' },
      ],
    },
    {
      key: 'sku_name',
      label: 'SKU',
      type: 'select',
      required: true,
      group: 'General',
      order: 3,
      defaultValue: 'GP_Standard_D2ds_v4',
      options: [
        { label: 'B1ms — Burstable (1 vCPU, 2 GB)', value: 'B_Standard_B1ms' },
        { label: 'B2s — Burstable (2 vCPU, 4 GB)', value: 'B_Standard_B2s' },
        { label: 'D2ds v4 — General Purpose (2 vCPU, 8 GB)', value: 'GP_Standard_D2ds_v4' },
        { label: 'D4ds v4 — General Purpose (4 vCPU, 16 GB)', value: 'GP_Standard_D4ds_v4' },
        { label: 'D8ds v4 — General Purpose (8 vCPU, 32 GB)', value: 'GP_Standard_D8ds_v4' },
        { label: 'E4ds v4 — Memory Optimized (4 vCPU, 32 GB)', value: 'MO_Standard_E4ds_v4' },
      ],
    },
    {
      key: 'administrator_login',
      label: 'Admin Username',
      type: 'string',
      required: true,
      group: 'Authentication',
      order: 4,
      defaultValue: 'mysqladmin',
      placeholder: 'mysqladmin',
      validation: {
        minLength: 1,
        maxLength: 63,
      },
    },
    {
      key: 'administrator_password',
      label: 'Admin Password',
      type: 'string',
      required: true,
      sensitive: true,
      group: 'Authentication',
      order: 5,
      description: 'Will be stored as a sensitive Terraform variable',
      validation: {
        minLength: 8,
        maxLength: 128,
      },
    },
    {
      key: 'storage_size_gb',
      label: 'Storage (GB)',
      type: 'select',
      required: false,
      group: 'Storage',
      order: 6,
      defaultValue: '20',
      options: [
        { label: '20 GB', value: '20' },
        { label: '32 GB', value: '32' },
        { label: '64 GB', value: '64' },
        { label: '128 GB', value: '128' },
        { label: '256 GB', value: '256' },
        { label: '512 GB', value: '512' },
        { label: '1 TB', value: '1024' },
      ],
    },
    {
      key: 'backup_retention_days',
      label: 'Backup Retention (days)',
      type: 'number',
      required: false,
      group: 'Storage',
      order: 7,
      defaultValue: 7,
      validation: {
        min: 1,
        max: 35,
      },
    },
    {
      key: 'geo_redundant_backup_enabled',
      label: 'Geo-Redundant Backup',
      type: 'boolean',
      required: false,
      group: 'Backup',
      order: 8,
      defaultValue: false,
    },
    {
      key: 'ha_enabled',
      label: 'High Availability',
      type: 'boolean',
      required: false,
      group: 'High Availability',
      order: 9,
      defaultValue: false,
    },
    {
      key: 'ha_mode',
      label: 'HA Mode',
      type: 'select',
      required: false,
      group: 'High Availability',
      order: 10,
      defaultValue: 'ZoneRedundant',
      options: [
        { label: 'Zone Redundant', value: 'ZoneRedundant' },
        { label: 'Same Zone', value: 'SameZone' },
      ],
      visibleWhen: { field: 'ha_enabled', operator: 'truthy' as const },
    },
    {
      key: 'maintenance_day',
      label: 'Maintenance Day',
      type: 'select',
      required: false,
      group: 'Maintenance',
      order: 11,
      options: [
        { label: 'Sunday', value: '0' },
        { label: 'Monday', value: '1' },
        { label: 'Tuesday', value: '2' },
        { label: 'Wednesday', value: '3' },
        { label: 'Thursday', value: '4' },
        { label: 'Friday', value: '5' },
        { label: 'Saturday', value: '6' },
      ],
    },
    {
      key: 'maintenance_hour',
      label: 'Maintenance Start Hour',
      type: 'number',
      required: false,
      group: 'Maintenance',
      order: 12,
      validation: {
        min: 0,
        max: 23,
      },
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'fqdn', label: 'Fully Qualified Domain Name', terraformAttribute: 'fqdn' },
  ],

  costEstimation: {
    serviceName: 'Azure Database for MySQL',
    skuProperty: 'sku_name',
  },
};
