import type { ResourceSchema } from '@terrastudio/types';

export const ecsTaskDefinitionSchema: ResourceSchema = {
  typeId: 'aws/containers/ecs_task_definition',
  provider: 'aws',
  displayName: 'ECS Task Definition',
  category: 'aws-containers',
  description: 'Task definition describing container configurations for ECS',
  terraformType: 'aws_ecs_task_definition',
  supportsTags: true,
  requiresResourceGroup: false,
  canBeChildOf: ['aws/containers/ecs_cluster'],
  parentReference: { propertyKey: 'cluster_arn' },

  properties: [
    {
      key: 'family',
      label: 'Family',
      type: 'string',
      required: true,
      placeholder: 'my-app',
      group: 'General',
      order: 1,
      description: 'Task definition family name (groups revisions)',
    },
    {
      key: 'cpu',
      label: 'CPU (units)',
      type: 'select',
      required: true,
      defaultValue: '256',
      options: [
        { label: '0.25 vCPU (256)', value: '256' },
        { label: '0.5 vCPU (512)', value: '512' },
        { label: '1 vCPU (1024)', value: '1024' },
        { label: '2 vCPU (2048)', value: '2048' },
        { label: '4 vCPU (4096)', value: '4096' },
      ],
      group: 'Resources',
      order: 2,
    },
    {
      key: 'memory',
      label: 'Memory (MiB)',
      type: 'select',
      required: true,
      defaultValue: '512',
      options: [
        { label: '512 MiB', value: '512' },
        { label: '1024 MiB (1 GB)', value: '1024' },
        { label: '2048 MiB (2 GB)', value: '2048' },
        { label: '4096 MiB (4 GB)', value: '4096' },
        { label: '8192 MiB (8 GB)', value: '8192' },
      ],
      group: 'Resources',
      order: 3,
    },
    {
      key: 'network_mode',
      label: 'Network Mode',
      type: 'select',
      required: false,
      defaultValue: 'awsvpc',
      options: [
        { label: 'awsvpc (recommended for Fargate)', value: 'awsvpc' },
        { label: 'bridge', value: 'bridge' },
        { label: 'host', value: 'host' },
        { label: 'none', value: 'none' },
      ],
      group: 'Network',
      order: 4,
    },
    {
      key: 'container_image',
      label: 'Container Image',
      type: 'string',
      required: true,
      placeholder: 'nginx:latest',
      group: 'Container',
      order: 5,
      description: 'Docker image for the primary container',
    },
    {
      key: 'container_port',
      label: 'Container Port',
      type: 'number',
      required: false,
      defaultValue: 80,
      group: 'Container',
      order: 6,
      validation: { min: 1, max: 65535 },
    },
    {
      key: 'requires_compatibilities',
      label: 'Launch Type',
      type: 'select',
      required: false,
      defaultValue: 'FARGATE',
      options: [
        { label: 'Fargate', value: 'FARGATE' },
        { label: 'EC2', value: 'EC2' },
      ],
      group: 'General',
      order: 7,
    },
  ],

  handles: [
    { id: 'taskdef-out', type: 'source', position: 'right', label: 'Task Def' },
  ],

  outputs: [
    { key: 'arn', label: 'ARN', terraformAttribute: 'arn' },
    { key: 'revision', label: 'Revision', terraformAttribute: 'revision' },
  ],

  costEstimation: {
    serviceName: 'Amazon ECS',
    staticMonthlyCost: 0,
  },
};
