import type { ResourceSchema } from '@terrastudio/types';

export const kubernetesClusterSchema: ResourceSchema = {
  typeId: 'azurerm/containers/kubernetes_cluster',
  provider: 'azurerm',
  displayName: 'AKS Cluster',
  category: 'containers',
  description: 'Azure Kubernetes Service — managed Kubernetes cluster',
  terraformType: 'azurerm_kubernetes_cluster',
  supportsTags: true,
  requiresResourceGroup: true,
  cafAbbreviation: 'aks',
  namingConstraints: { maxLength: 63 },
  isContainer: true,
  canBeChildOf: [
    'azurerm/core/resource_group',
    'azurerm/networking/subnet',
  ],
  visualContainment: true,
  containerStyle: {
    borderColor: '#326CE5',
    borderStyle: 'solid',
    backgroundColor: '#ffffff',
    headerColor: '#1a1a2e',
    borderRadius: 12,
    borderWidth: 3,
    hideHeaderBorder: true,
    iconSize: 28,
    labelSize: 16,
  },
  minSize: { width: 280, height: 200 },

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'aks-myapp-dev',
      group: 'General',
      order: 1,
      validation: {
        minLength: 1,
        maxLength: 63,
        pattern: '^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]$',
        patternMessage: 'Alphanumerics and hyphens, must start and end with alphanumeric',
      },
    },
    {
      key: 'dns_prefix',
      label: 'DNS Prefix',
      type: 'string',
      required: true,
      placeholder: 'myapp',
      group: 'General',
      order: 2,
      description: 'DNS prefix for the Kubernetes API server FQDN',
      validation: {
        minLength: 1,
        maxLength: 54,
        pattern: '^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]$',
        patternMessage: 'Alphanumerics and hyphens, must start and end with alphanumeric',
      },
    },
    {
      key: 'kubernetes_version',
      label: 'Kubernetes Version',
      type: 'select',
      required: false,
      group: 'General',
      order: 3,
      defaultValue: '1.31',
      options: [
        { label: '1.29', value: '1.29' },
        { label: '1.30', value: '1.30' },
        { label: '1.31', value: '1.31' },
      ],
    },
    {
      key: 'sku_tier',
      label: 'SKU Tier',
      type: 'select',
      required: false,
      group: 'General',
      order: 4,
      defaultValue: 'Free',
      description: 'Standard includes uptime SLA',
      options: [
        { label: 'Free', value: 'Free' },
        { label: 'Standard', value: 'Standard' },
      ],
    },

    // Network
    {
      key: 'network_plugin',
      label: 'Network Plugin',
      type: 'select',
      required: false,
      group: 'Network',
      order: 10,
      defaultValue: 'azure',
      description: 'Azure CNI (pods get VNet IPs) or Kubenet (basic overlay)',
      options: [
        { label: 'Azure CNI', value: 'azure' },
        { label: 'Kubenet', value: 'kubenet' },
      ],
    },

    // Identity
    {
      key: 'identity_type',
      label: 'Identity Type',
      type: 'select',
      required: false,
      group: 'Identity',
      order: 20,
      defaultValue: 'SystemAssigned',
      options: [
        { label: 'System Assigned', value: 'SystemAssigned' },
        { label: 'User Assigned', value: 'UserAssigned' },
      ],
    },

    // Default Node Pool
    {
      key: 'default_pool_name',
      label: 'Pool Name',
      type: 'string',
      required: false,
      group: 'Default Node Pool',
      order: 30,
      defaultValue: 'default',
      validation: {
        minLength: 1,
        maxLength: 12,
        pattern: '^[a-z][a-z0-9]*$',
        patternMessage: 'Lowercase alphanumeric, must start with a letter, max 12 characters',
      },
    },
    {
      key: 'default_pool_vm_size',
      label: 'VM Size',
      type: 'select',
      required: true,
      group: 'Default Node Pool',
      order: 31,
      defaultValue: 'Standard_B2s',
      options: [
        { label: 'Standard_B2s (2 vCPU, 4 GB)', value: 'Standard_B2s' },
        { label: 'Standard_B4ms (4 vCPU, 16 GB)', value: 'Standard_B4ms' },
        { label: 'Standard_DS2_v2 (2 vCPU, 7 GB)', value: 'Standard_DS2_v2' },
        { label: 'Standard_DS3_v2 (4 vCPU, 14 GB)', value: 'Standard_DS3_v2' },
        { label: 'Standard_D4s_v3 (4 vCPU, 16 GB)', value: 'Standard_D4s_v3' },
        { label: 'Standard_D8s_v3 (8 vCPU, 32 GB)', value: 'Standard_D8s_v3' },
        { label: 'Standard_E4s_v3 (4 vCPU, 32 GB)', value: 'Standard_E4s_v3' },
      ],
    },
    {
      key: 'default_pool_count',
      label: 'Node Count',
      type: 'number',
      required: false,
      group: 'Default Node Pool',
      order: 32,
      defaultValue: 1,
      description: 'Initial node count (ignored when auto-scaling is enabled)',
      validation: { min: 1, max: 100 },
    },
    {
      key: 'default_pool_auto_scaling',
      label: 'Auto Scaling',
      type: 'boolean',
      required: false,
      group: 'Default Node Pool',
      order: 33,
      defaultValue: false,
    },
    {
      key: 'default_pool_min_count',
      label: 'Min Nodes',
      type: 'number',
      required: false,
      group: 'Default Node Pool',
      order: 34,
      defaultValue: 1,
      validation: { min: 1, max: 100 },
      visibleWhen: { field: 'default_pool_auto_scaling', operator: 'truthy' },
    },
    {
      key: 'default_pool_max_count',
      label: 'Max Nodes',
      type: 'number',
      required: false,
      group: 'Default Node Pool',
      order: 35,
      defaultValue: 3,
      validation: { min: 1, max: 100 },
      visibleWhen: { field: 'default_pool_auto_scaling', operator: 'truthy' },
    },
  ],

  handles: [
    {
      id: 'pep-target',
      type: 'target',
      position: 'left',
      label: 'Private Endpoint',
    },
    {
      id: 'acr-link',
      type: 'target',
      position: 'left',
      label: 'Container Registry',
    },
    {
      id: 'subnet-in',
      type: 'target',
      position: 'left',
      label: 'Subnet',
    },
  ],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'fqdn', label: 'FQDN', terraformAttribute: 'fqdn' },
    { key: 'kube_config_raw', label: 'Kubeconfig', terraformAttribute: 'kube_config_raw', sensitive: true },
    { key: 'kubelet_identity_object_id', label: 'Kubelet Identity Object ID', terraformAttribute: 'kubelet_identity[0].object_id' },
  ],

  costEstimation: {
    serviceName: 'Azure Kubernetes Service',
    skuProperty: 'sku_tier',
  },
};
