import type { ResourceSchema } from '@terrastudio/types';

export const cognitiveDeploymentSchema: ResourceSchema = {
  typeId: 'azurerm/ai/cognitive_deployment',
  provider: 'azurerm',
  displayName: 'Cognitive Deployment',
  category: 'ai',
  description: 'Azure Cognitive Services model deployment (e.g., GPT-4o, embeddings)',
  terraformType: 'azurerm_cognitive_deployment',
  supportsTags: false,
  requiresResourceGroup: false,
  cafAbbreviation: 'cogd',
  canBeChildOf: ['azurerm/core/resource_group'],
  visualContainment: true,

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'gpt-4o-deployment',
      group: 'General',
      order: 1,
    },
    {
      key: 'model_format',
      label: 'Model Format',
      type: 'select',
      required: true,
      group: 'Model',
      order: 2,
      defaultValue: 'OpenAI',
      options: [
        { label: 'OpenAI', value: 'OpenAI' },
        { label: 'Cohere', value: 'Cohere' },
        { label: 'Meta', value: 'Meta' },
        { label: 'Mistral', value: 'Mistral' },
      ],
    },
    {
      key: 'model_name',
      label: 'Model Name',
      type: 'select',
      required: true,
      group: 'Model',
      order: 3,
      defaultValue: 'gpt-4o',
      options: [
        { label: 'GPT-4o', value: 'gpt-4o' },
        { label: 'GPT-4', value: 'gpt-4' },
        { label: 'GPT-4 32K', value: 'gpt-4-32k' },
        { label: 'GPT-3.5 Turbo', value: 'gpt-35-turbo' },
        { label: 'GPT-3.5 Turbo 16K', value: 'gpt-35-turbo-16k' },
        { label: 'Text Embedding Ada 002', value: 'text-embedding-ada-002' },
        { label: 'Text Embedding 3 Small', value: 'text-embedding-3-small' },
        { label: 'Text Embedding 3 Large', value: 'text-embedding-3-large' },
        { label: 'DALL-E 3', value: 'dall-e-3' },
        { label: 'Whisper', value: 'whisper' },
        { label: 'TTS', value: 'tts' },
        { label: 'TTS HD', value: 'tts-hd' },
      ],
    },
    {
      key: 'model_version',
      label: 'Model Version',
      type: 'string',
      required: false,
      group: 'Model',
      order: 4,
      placeholder: 'latest',
    },
    {
      key: 'sku_name',
      label: 'SKU',
      type: 'select',
      required: true,
      group: 'Scale',
      order: 5,
      defaultValue: 'Standard',
      options: [
        { label: 'Standard', value: 'Standard' },
        { label: 'Global Standard', value: 'GlobalStandard' },
        { label: 'Provisioned Managed', value: 'ProvisionedManaged' },
        { label: 'Data Zone Standard', value: 'DataZoneStandard' },
      ],
    },
    {
      key: 'sku_capacity',
      label: 'SKU Capacity',
      type: 'number',
      required: false,
      group: 'Scale',
      order: 6,
      description: 'Tokens per minute capacity (in thousands)',
    },
    {
      key: 'version_upgrade_option',
      label: 'Version Upgrade Option',
      type: 'select',
      required: false,
      group: 'Advanced',
      order: 7,
      defaultValue: 'OnceNewDefaultVersionAvailable',
      options: [
        { label: 'Once New Default Version Available', value: 'OnceNewDefaultVersionAvailable' },
        { label: 'Once Current Version Expired', value: 'OnceCurrentVersionExpired' },
        { label: 'No Auto Upgrade', value: 'NoAutoUpgrade' },
      ],
    },
    {
      key: 'rai_policy_name',
      label: 'RAI Policy Name',
      type: 'string',
      required: false,
      group: 'Advanced',
      order: 8,
      description: 'RAI content filter policy name',
    },
  ],

  handles: [
    {
      id: 'cognitive-account-in',
      type: 'target',
      position: 'left',
      label: 'AI Account',
    },
    {
      id: 'raip-in',
      type: 'target',
      position: 'left',
      label: 'RAI Policy',
    },
  ],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
  ],
};
