import type { ResourceSchema } from '@terrastudio/types';

export const rdsInstanceSchema: ResourceSchema = {
  typeId: 'aws/compute/rds_instance',
  provider: 'aws',
  displayName: 'RDS Instance',
  category: 'aws-database',
  description: 'AWS RDS managed relational database instance',
  terraformType: 'aws_db_instance',
  supportsTags: true,
  requiresResourceGroup: false,
  canBeChildOf: ['aws/networking/vpc'],

  properties: [
    {
      key: 'name',
      label: 'Identifier',
      type: 'string',
      required: true,
      placeholder: 'my-database',
      group: 'General',
      order: 1,
    },
    {
      key: 'engine',
      label: 'Engine',
      type: 'select',
      required: true,
      defaultValue: 'postgres',
      group: 'General',
      order: 2,
      options: [
        { label: 'MySQL', value: 'mysql' },
        { label: 'PostgreSQL', value: 'postgres' },
        { label: 'MariaDB', value: 'mariadb' },
        { label: 'SQL Server Express', value: 'sqlserver-ex' },
        { label: 'Oracle Enterprise', value: 'oracle-ee' },
      ],
    },
    {
      key: 'engine_version',
      label: 'Engine Version',
      type: 'string',
      required: false,
      placeholder: '16.3',
      group: 'General',
      order: 3,
    },
    {
      key: 'instance_class',
      label: 'Instance Class',
      type: 'select',
      required: true,
      defaultValue: 'db.t3.micro',
      group: 'General',
      order: 4,
      options: [
        { label: 'db.t3.micro', value: 'db.t3.micro' },
        { label: 'db.t3.small', value: 'db.t3.small' },
        { label: 'db.t3.medium', value: 'db.t3.medium' },
        { label: 'db.t3.large', value: 'db.t3.large' },
        { label: 'db.m5.large', value: 'db.m5.large' },
        { label: 'db.m5.xlarge', value: 'db.m5.xlarge' },
        { label: 'db.r5.large', value: 'db.r5.large' },
      ],
    },
    {
      key: 'allocated_storage',
      label: 'Allocated Storage (GB)',
      type: 'number',
      required: false,
      defaultValue: 20,
      description: 'Storage in GB',
      group: 'Storage',
      order: 5,
    },
    {
      key: 'storage_type',
      label: 'Storage Type',
      type: 'select',
      required: false,
      defaultValue: 'gp3',
      group: 'Storage',
      order: 6,
      options: [
        { label: 'gp3', value: 'gp3' },
        { label: 'gp2', value: 'gp2' },
        { label: 'io1', value: 'io1' },
        { label: 'io2', value: 'io2' },
      ],
    },
    {
      key: 'db_name',
      label: 'Database Name',
      type: 'string',
      required: false,
      placeholder: 'mydb',
      group: 'Database',
      order: 7,
    },
    {
      key: 'username',
      label: 'Username',
      type: 'string',
      required: true,
      placeholder: 'admin',
      group: 'Database',
      order: 8,
    },
    {
      key: 'password',
      label: 'Password',
      type: 'string',
      required: true,
      sensitive: true,
      placeholder: 'changeme',
      group: 'Database',
      order: 9,
    },
    {
      key: 'multi_az',
      label: 'Multi-AZ',
      type: 'boolean',
      required: false,
      defaultValue: false,
      group: 'Availability',
      order: 10,
    },
    {
      key: 'publicly_accessible',
      label: 'Publicly Accessible',
      type: 'boolean',
      required: false,
      defaultValue: false,
      group: 'Networking',
      order: 11,
    },
    {
      key: 'skip_final_snapshot',
      label: 'Skip Final Snapshot',
      type: 'boolean',
      required: false,
      defaultValue: true,
      group: 'Advanced',
      order: 12,
    },
    {
      key: 'sg_enabled',
      label: 'Security Group',
      type: 'boolean',
      required: false,
      defaultValue: false,
      description: 'Associate a Security Group',
      group: 'Security',
      order: 13,
    },
    {
      key: 'security_group_ids',
      label: 'Security Group',
      type: 'reference',
      required: false,
      referenceTargetTypes: ['aws/compute/security_group'],
      group: 'Security',
      order: 14,
      visibleWhen: { field: 'sg_enabled', operator: 'truthy' },
    },
    {
      key: 'iam_database_authentication_enabled',
      label: 'IAM Database Authentication',
      type: 'boolean',
      required: false,
      defaultValue: false,
      group: 'Security',
      order: 15,
    },
    // Backup
    {
      key: 'backup_retention_period',
      label: 'Backup Retention (days)',
      type: 'number',
      required: false,
      defaultValue: 7,
      validation: { min: 0, max: 35 },
      description: '0 disables automated backups',
      group: 'Backup',
      order: 20,
    },
    {
      key: 'backup_window',
      label: 'Backup Window',
      type: 'string',
      required: false,
      placeholder: '03:00-04:00',
      description: 'Preferred UTC backup window (hh24:mi-hh24:mi)',
      group: 'Backup',
      order: 21,
    },
    // Maintenance
    {
      key: 'maintenance_window',
      label: 'Maintenance Window',
      type: 'string',
      required: false,
      placeholder: 'sun:05:00-sun:06:00',
      description: 'Preferred UTC maintenance window (ddd:hh24:mi-ddd:hh24:mi)',
      group: 'Maintenance',
      order: 30,
    },
    // Configuration
    {
      key: 'parameter_group_name',
      label: 'Parameter Group',
      type: 'string',
      required: false,
      description: 'Name of the DB parameter group',
      group: 'Configuration',
      order: 40,
    },
    {
      key: 'option_group_name',
      label: 'Option Group',
      type: 'string',
      required: false,
      description: 'Name of the DB option group',
      group: 'Configuration',
      order: 41,
    },
    // Monitoring
    {
      key: 'monitoring_interval',
      label: 'Enhanced Monitoring Interval',
      type: 'select',
      required: false,
      defaultValue: '0',
      group: 'Monitoring',
      order: 50,
      options: [
        { label: 'Disabled', value: '0' },
        { label: '1 second', value: '1' },
        { label: '5 seconds', value: '5' },
        { label: '10 seconds', value: '10' },
        { label: '15 seconds', value: '15' },
        { label: '30 seconds', value: '30' },
        { label: '60 seconds', value: '60' },
      ],
    },
    // Networking
    {
      key: 'db_subnet_group_name',
      label: 'DB Subnet Group',
      type: 'string',
      required: false,
      description: 'Name of the DB subnet group for VPC placement',
      group: 'Networking',
      order: 12,
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'DB Instance ID', terraformAttribute: 'id' },
    { key: 'arn', label: 'ARN', terraformAttribute: 'arn' },
    { key: 'endpoint', label: 'Endpoint', terraformAttribute: 'endpoint' },
    { key: 'address', label: 'Address', terraformAttribute: 'address' },
    { key: 'port', label: 'Port', terraformAttribute: 'port' },
  ],

  costEstimation: {
    serviceName: 'RDS',
    skuProperty: 'instance_class',
  },
};
