import type { ResourceSchema } from '@terrastudio/types';

export const signalrServiceSchema: ResourceSchema = {
	typeId: 'azurerm/web/signalr_service',
	provider: 'azurerm',
	displayName: 'SignalR Service',
	category: 'web',
	description: 'Azure SignalR Service for real-time web communication',
	terraformType: 'azurerm_signalr_service',
	supportsTags: true,
	requiresResourceGroup: true,
	cafAbbreviation: 'sigr',
	canBeChildOf: ['azurerm/core/resource_group'],
	privateEndpointConfig: {
		subresources: [{ key: 'signalr', label: 'SignalR Service' }],
		defaultSubresource: 'signalr',
	},
	properties: [
		{
			key: 'name',
			label: 'Name',
			type: 'string',
			required: true,
			placeholder: 'sigr-myapp-dev',
			group: 'General',
			order: 1,
			validation: {
				minLength: 3,
				maxLength: 63,
				pattern: '^[a-zA-Z][a-zA-Z0-9-]*[a-zA-Z0-9]$',
				patternMessage: 'Must start with letter, alphanumerics and hyphens',
			},
		},
		{
			key: 'sku_name',
			label: 'SKU',
			type: 'select',
			required: true,
			group: 'General',
			order: 2,
			defaultValue: 'Free_F1',
			options: [
				{ label: 'Free F1', value: 'Free_F1' },
				{ label: 'Standard S1', value: 'Standard_S1' },
				{ label: 'Premium P1', value: 'Premium_P1' },
			],
		},
		{
			key: 'capacity',
			label: 'Capacity',
			type: 'select',
			required: false,
			group: 'General',
			order: 3,
			defaultValue: '1',
			description: 'Number of units (Free tier is always 1)',
			options: [
				{ label: '1', value: '1' },
				{ label: '2', value: '2' },
				{ label: '5', value: '5' },
				{ label: '10', value: '10' },
				{ label: '20', value: '20' },
				{ label: '50', value: '50' },
				{ label: '100', value: '100' },
			],
		},
		{
			key: 'service_mode',
			label: 'Service Mode',
			type: 'select',
			required: false,
			group: 'Configuration',
			order: 4,
			defaultValue: 'Default',
			options: [
				{ label: 'Default', value: 'Default' },
				{ label: 'Serverless', value: 'Serverless' },
				{ label: 'Classic', value: 'Classic' },
			],
		},
		{
			key: 'connectivity_logs_enabled',
			label: 'Connectivity Logs',
			type: 'boolean',
			required: false,
			group: 'Logging',
			order: 5,
			defaultValue: false,
		},
		{
			key: 'messaging_logs_enabled',
			label: 'Messaging Logs',
			type: 'boolean',
			required: false,
			group: 'Logging',
			order: 6,
			defaultValue: false,
		},
		{
			key: 'live_trace_enabled',
			label: 'Live Trace',
			type: 'boolean',
			required: false,
			group: 'Logging',
			order: 7,
			defaultValue: false,
		},
	],
	handles: [{ id: 'pep-target', type: 'target', position: 'left', label: 'Private Endpoint' }],
	outputs: [
		{ key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
		{ key: 'hostname', label: 'Hostname', terraformAttribute: 'hostname' },
		{
			key: 'primary_connection_string',
			label: 'Primary Connection String',
			terraformAttribute: 'primary_connection_string',
			sensitive: true,
		},
		{
			key: 'primary_access_key',
			label: 'Primary Access Key',
			terraformAttribute: 'primary_access_key',
			sensitive: true,
		},
	],

	costEstimation: {
		serviceName: 'SignalR Service',
		skuProperty: 'sku_name',
	},
};
