import type { ResourceSchema } from '@terrastudio/types';

export const mssqlManagedInstanceSchema: ResourceSchema = {
  typeId: 'azurerm/database/mssql_managed_instance',
  provider: 'azurerm',
  displayName: 'SQL Managed Instance',
  category: 'managed-instance',
  description: 'Azure SQL Managed Instance — fully managed SQL Server with full compatibility',
  terraformType: 'azurerm_mssql_managed_instance',
  supportsTags: true,
  requiresResourceGroup: true,
  cafAbbreviation: 'sqlmi',
  namingConstraints: { lowercase: true, maxLength: 63 },
  isContainer: true,

  canBeChildOf: [
    'azurerm/core/resource_group',
  ],
  visualContainment: true,

  containerStyle: {
    borderColor: '#2B7CF6',
    borderStyle: 'dotted',
    backgroundColor: '#ffffff',
    headerColor: '#1a1a2e',
    borderRadius: 12,
    borderWidth: 3,
    hideHeaderBorder: true,
    iconSize: 28,
    labelSize: 16,
    dashArray: '4,8',
  },

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'sqlmi-myapp-dev',
      group: 'General',
      order: 1,
      description: 'Globally unique instance name',
      validation: {
        minLength: 1,
        maxLength: 63,
        pattern: '^[a-z0-9][a-z0-9-]*[a-z0-9]$',
        patternMessage: 'Lowercase alphanumeric and hyphens only, must start and end with alphanumeric',
      },
    },
    {
      key: 'sku_name',
      label: 'SKU',
      type: 'select',
      required: true,
      group: 'Compute',
      order: 2,
      defaultValue: 'GP_Gen5',
      options: [
        { label: 'General Purpose Gen5', value: 'GP_Gen5' },
        { label: 'Business Critical Gen5', value: 'BC_Gen5' },
        { label: 'General Purpose Gen8IM (Memory Optimised)', value: 'GP_Gen8IM' },
        { label: 'Business Critical Gen8IM', value: 'BC_Gen8IM' },
        { label: 'General Purpose Gen8IH (High Perf)', value: 'GP_Gen8IH' },
        { label: 'Business Critical Gen8IH', value: 'BC_Gen8IH' },
      ],
    },
    {
      key: 'vcores',
      label: 'vCores',
      type: 'select',
      required: true,
      group: 'Compute',
      order: 3,
      defaultValue: '4',
      options: [
        { label: '4', value: '4' },
        { label: '8', value: '8' },
        { label: '16', value: '16' },
        { label: '24', value: '24' },
        { label: '32', value: '32' },
        { label: '40', value: '40' },
        { label: '64', value: '64' },
        { label: '80', value: '80' },
      ],
    },
    {
      key: 'storage_size_in_gb',
      label: 'Storage (GB)',
      type: 'number',
      required: true,
      group: 'Compute',
      order: 4,
      defaultValue: 32,
      validation: { min: 32, max: 16384 },
    },
    {
      key: 'license_type',
      label: 'License Type',
      type: 'select',
      required: true,
      group: 'Compute',
      order: 5,
      defaultValue: 'LicenseIncluded',
      options: [
        { label: 'License Included', value: 'LicenseIncluded' },
        { label: 'Base Price (Azure Hybrid Benefit)', value: 'BasePrice' },
      ],
    },
    {
      key: 'administrator_login',
      label: 'Admin Login',
      type: 'string',
      required: true,
      group: 'Authentication',
      order: 10,
      placeholder: 'sqladmin',
      validation: {
        minLength: 1,
        maxLength: 128,
        pattern: '^[a-zA-Z][a-zA-Z0-9_]*$',
        patternMessage: 'Must start with a letter, followed by letters, digits, or underscores',
      },
    },
    {
      key: 'administrator_login_password',
      label: 'Admin Password',
      type: 'string',
      required: true,
      sensitive: true,
      group: 'Authentication',
      order: 11,
      description: 'Will be stored as a sensitive Terraform variable',
      validation: {
        minLength: 8,
        maxLength: 128,
      },
    },
    {
      key: 'subnet_id',
      label: 'Subnet',
      type: 'reference',
      required: true,
      group: 'Networking',
      order: 20,
      referenceTargetTypes: ['azurerm/networking/subnet'],
      description: 'Dedicated subnet delegated to Microsoft.Sql/managedInstances',
    },
    {
      key: 'minimum_tls_version',
      label: 'Minimum TLS Version',
      type: 'select',
      required: false,
      group: 'Security',
      order: 21,
      defaultValue: '1.2',
      options: [
        { label: 'TLS 1.0', value: '1.0' },
        { label: 'TLS 1.1', value: '1.1' },
        { label: 'TLS 1.2', value: '1.2' },
      ],
    },
    {
      key: 'public_data_endpoint_enabled',
      label: 'Public Data Endpoint',
      type: 'boolean',
      required: false,
      group: 'Security',
      order: 22,
      defaultValue: false,
    },
    {
      key: 'proxy_override',
      label: 'Proxy Override',
      type: 'select',
      required: false,
      group: 'Networking',
      order: 23,
      defaultValue: 'Default',
      options: [
        { label: 'Default', value: 'Default' },
        { label: 'Proxy', value: 'Proxy' },
        { label: 'Redirect', value: 'Redirect' },
      ],
    },
    {
      key: 'timezone_id',
      label: 'Timezone',
      type: 'string',
      required: false,
      group: 'Advanced',
      order: 30,
      defaultValue: 'UTC',
      description: 'Windows timezone ID (cannot be changed after creation)',
    },
    {
      key: 'collation',
      label: 'Collation',
      type: 'string',
      required: false,
      group: 'Advanced',
      order: 31,
      defaultValue: 'SQL_Latin1_General_CP1_CI_AS',
    },
    {
      key: 'identity_enabled',
      label: 'Managed Identity',
      type: 'boolean',
      required: false,
      group: 'Identity',
      order: 40,
      defaultValue: false,
    },
    {
      key: 'identity_type',
      label: 'Identity Type',
      type: 'select',
      required: false,
      group: 'Identity',
      order: 41,
      defaultValue: 'SystemAssigned',
      visibleWhen: { field: 'identity_enabled', operator: 'truthy' },
      options: [
        { label: 'System Assigned', value: 'SystemAssigned' },
        { label: 'User Assigned', value: 'UserAssigned' },
        { label: 'System & User Assigned', value: 'SystemAssigned, UserAssigned' },
      ],
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'fqdn', label: 'FQDN', terraformAttribute: 'fqdn' },
  ],

  costEstimation: {
    serviceName: 'SQL Managed Instance',
    skuProperty: 'sku_name',
    staticMonthlyCost: 0,
  },
};
