import type { ResourceSchema } from '@terrastudio/types';

export const federatedIdentityCredentialSchema: ResourceSchema = {
  typeId: 'azurerm/identity/federated_identity_credential',
  provider: 'azurerm',
  displayName: 'Federated Credential',
  category: 'identity',
  description: 'Binds a User-Assigned Managed Identity to an external OIDC provider (GitHub, Azure DevOps, Kubernetes)',
  terraformType: 'azurerm_federated_identity_credential',
  supportsTags: false,
  requiresResourceGroup: true,
  cafAbbreviation: 'fic',
  namingConstraints: { maxLength: 120 },

  canBeChildOf: [
    'azurerm/core/resource_group',
  ],

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'fic-github-main',
      group: 'General',
      order: 1,
      validation: { minLength: 3, maxLength: 120 },
    },
    {
      key: 'parent_id',
      label: 'Managed Identity',
      type: 'reference',
      required: true,
      group: 'General',
      order: 2,
      referenceTargetTypes: ['azurerm/identity/user_assigned_identity'],
      description: 'The User-Assigned Managed Identity that receives the federated credential',
    },
    {
      key: 'preset',
      label: 'Preset',
      type: 'select',
      required: false,
      group: 'Federation',
      order: 3,
      defaultValue: 'custom',
      options: [
        { label: 'Custom (manual issuer + subject)', value: 'custom' },
        { label: 'GitHub Actions — Branch', value: 'github_branch' },
        { label: 'GitHub Actions — Pull Request', value: 'github_pr' },
        { label: 'GitHub Actions — Environment', value: 'github_env' },
        { label: 'GitHub Actions — Tag', value: 'github_tag' },
        { label: 'Azure DevOps Pipeline', value: 'azdo' },
        { label: 'Kubernetes Service Account', value: 'k8s' },
      ],
    },
    {
      key: 'issuer',
      label: 'Issuer',
      type: 'string',
      required: true,
      group: 'Federation',
      order: 4,
      placeholder: 'https://token.actions.githubusercontent.com',
      visibleWhen: { field: 'preset', operator: 'eq', value: 'custom' },
    },
    {
      key: 'subject',
      label: 'Subject',
      type: 'string',
      required: true,
      group: 'Federation',
      order: 5,
      placeholder: 'repo:owner/repo:ref:refs/heads/main',
      visibleWhen: { field: 'preset', operator: 'eq', value: 'custom' },
    },
    {
      key: 'github_org',
      label: 'GitHub Org/Owner',
      type: 'string',
      required: false,
      group: 'Federation',
      order: 6,
      placeholder: 'my-org',
      visibleWhen: { field: 'preset', operator: 'in', value: ['github_branch', 'github_pr', 'github_env', 'github_tag'] },
    },
    {
      key: 'github_repo',
      label: 'GitHub Repo',
      type: 'string',
      required: false,
      group: 'Federation',
      order: 7,
      placeholder: 'my-repo',
      visibleWhen: { field: 'preset', operator: 'in', value: ['github_branch', 'github_pr', 'github_env', 'github_tag'] },
    },
    {
      key: 'github_ref',
      label: 'Branch / Tag',
      type: 'string',
      required: false,
      group: 'Federation',
      order: 8,
      placeholder: 'main',
      visibleWhen: { field: 'preset', operator: 'in', value: ['github_branch', 'github_tag'] },
    },
    {
      key: 'github_environment',
      label: 'GitHub Environment',
      type: 'string',
      required: false,
      group: 'Federation',
      order: 9,
      placeholder: 'production',
      visibleWhen: { field: 'preset', operator: 'eq', value: 'github_env' },
    },
    {
      key: 'audience',
      label: 'Audience',
      type: 'array',
      required: false,
      group: 'Advanced',
      order: 20,
      description: 'Defaults to api://AzureADTokenExchange when unset',
      itemSchema: {
        key: 'audience',
        label: 'Audience',
        type: 'string',
        required: true,
        placeholder: 'api://AzureADTokenExchange',
      },
      defaultValue: ['api://AzureADTokenExchange'],
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
  ],

  costEstimation: { serviceName: 'Federated Identity Credential', staticMonthlyCost: 0 },
};
