import type { ResourceSchema } from '@terrastudio/types';

export const appServiceSchema: ResourceSchema = {
  typeId: 'azurerm/compute/app_service',
  provider: 'azurerm',
  displayName: 'App Service',
  category: 'compute',
  description: 'Azure App Service (Web App) for hosting web applications',
  terraformType: 'azurerm_linux_web_app',
  supportsTags: true,
  requiresResourceGroup: true,
  cafAbbreviation: 'app',
  namingConstraints: { maxLength: 60 },
  canBeChildOf: ['azurerm/core/resource_group', 'azurerm/networking/subnet'],
  visualContainment: true,
  privateEndpointConfig: {
    subresources: [
      { key: 'sites', label: 'App Service' },
    ],
    defaultSubresource: 'sites',
  },

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'app-mywebapp-dev',
      group: 'General',
      order: 1,
      validation: {
        minLength: 2,
        maxLength: 60,
        pattern: '^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]$',
        patternMessage: 'Alphanumerics and hyphens, must start and end with alphanumeric',
      },
    },
    {
      key: 'os_type',
      label: 'OS Type',
      type: 'select',
      required: true,
      group: 'General',
      order: 2,
      defaultValue: 'linux',
      description: 'Must match the App Service Plan OS type',
      options: [
        { label: 'Linux', value: 'linux' },
        { label: 'Windows', value: 'windows' },
      ],
    },
    {
      key: 'runtime_stack',
      label: 'Runtime Stack',
      type: 'select',
      required: false,
      group: 'Runtime',
      order: 3,
      defaultValue: 'NODE|18-lts',
      options: [
        { label: 'Node.js 18 LTS', value: 'NODE|18-lts' },
        { label: 'Node.js 20 LTS', value: 'NODE|20-lts' },
        { label: 'Python 3.11', value: 'PYTHON|3.11' },
        { label: 'Python 3.12', value: 'PYTHON|3.12' },
        { label: '.NET 8', value: 'DOTNETCORE|8.0' },
        { label: 'Java 17', value: 'JAVA|17-java17' },
        { label: 'PHP 8.2', value: 'PHP|8.2' },
      ],
    },
    {
      key: 'always_on',
      label: 'Always On',
      type: 'boolean',
      required: false,
      group: 'Configuration',
      order: 4,
      defaultValue: false,
      description: 'Keep the app loaded even when idle (requires Basic tier or higher)',
    },
    {
      key: 'https_only',
      label: 'HTTPS Only',
      type: 'boolean',
      required: false,
      group: 'Security',
      order: 5,
      defaultValue: true,
    },
    {
      key: 'client_cert_enabled',
      label: 'Client Certificate',
      type: 'boolean',
      required: false,
      group: 'Security',
      order: 6,
      defaultValue: false,
    },
    {
      key: 'minimum_tls_version',
      label: 'Minimum TLS Version',
      type: 'select',
      required: false,
      group: 'Security',
      order: 7,
      defaultValue: '1.2',
      options: [
        { label: '1.0', value: '1.0' },
        { label: '1.1', value: '1.1' },
        { label: '1.2 (recommended)', value: '1.2' },
      ],
    },
    {
      key: 'http2_enabled',
      label: 'HTTP/2',
      type: 'boolean',
      required: false,
      group: 'Site Config',
      order: 8,
      defaultValue: false,
    },
    {
      key: 'health_check_path',
      label: 'Health Check Path',
      type: 'string',
      required: false,
      group: 'Site Config',
      order: 9,
      placeholder: '/health',
    },
    {
      key: 'app_settings',
      label: 'Application Settings',
      type: 'key-value-map',
      required: false,
      group: 'Application Settings',
      order: 10,
      description: 'Environment variables for the app',
    },
    {
      key: 'identity_enabled',
      label: 'Enable Identity',
      type: 'boolean',
      required: false,
      group: 'Identity',
      order: 11,
      defaultValue: false,
    },
    {
      key: 'identity_type',
      label: 'Identity Type',
      type: 'select',
      required: false,
      group: 'Identity',
      order: 12,
      defaultValue: 'SystemAssigned',
      visibleWhen: { field: 'identity_enabled', operator: 'truthy' },
      options: [
        { label: 'System Assigned', value: 'SystemAssigned' },
        { label: 'User Assigned', value: 'UserAssigned' },
        { label: 'System & User Assigned', value: 'SystemAssigned, UserAssigned' },
      ],
    },
    {
      key: 'vnet_integration_subnet_id',
      label: 'VNet Integration Subnet',
      type: 'reference',
      required: false,
      group: 'Networking',
      order: 13,
      description: 'Subnet for outbound VNet integration (must have delegation for Microsoft.Web/serverFarms)',
      referenceTargetTypes: ['azurerm/networking/subnet'],
      showAsEdge: true,
    },
  ],

  handles: [
    {
      id: 'asp-in',
      type: 'target',
      position: 'top',
      label: 'Service Plan',
    },
    {
      id: 'pep-target',
      type: 'target',
      position: 'left',
      label: 'Private Endpoint',
    },
  ],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'default_hostname', label: 'Default Hostname', terraformAttribute: 'default_hostname' },
    { key: 'outbound_ip_addresses', label: 'Outbound IPs', terraformAttribute: 'outbound_ip_addresses' },
  ],

  costEstimation: {
    serviceName: 'Azure App Service',
    staticMonthlyCost: 0,
  },
};
