import type { ResourceSchema } from '@terrastudio/types';

export const storageAccountSchema: ResourceSchema = {
  typeId: 'azurerm/storage/storage_account',
  provider: 'azurerm',
  displayName: 'Storage Account',
  category: 'storage',
  description: 'Azure Storage Account for blobs, files, queues, and tables',
  terraformType: 'azurerm_storage_account',
  supportsTags: true,
  requiresResourceGroup: true,
  isContainer: true,
  canBeChildOf: [
    'azurerm/core/resource_group',
  ],
  containerStyle: {
    borderColor: '#37c2b1',
    borderStyle: 'dashed',
    backgroundColor: 'rgba(55, 194, 177, 0.06)',
    headerColor: '#37c2b1',
    borderRadius: 8,
  },

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'mystorageaccount',
      group: 'General',
      order: 1,
      validation: {
        minLength: 3,
        maxLength: 24,
        pattern: '^[a-z0-9]+$',
        patternMessage: 'Must be 3-24 lowercase letters and numbers only',
      },
    },
    {
      key: 'account_tier',
      label: 'Account Tier',
      type: 'select',
      required: true,
      group: 'General',
      order: 2,
      defaultValue: 'Standard',
      options: [
        { label: 'Standard', value: 'Standard' },
        { label: 'Premium', value: 'Premium' },
      ],
    },
    {
      key: 'account_replication_type',
      label: 'Replication',
      type: 'select',
      required: true,
      group: 'General',
      order: 3,
      defaultValue: 'LRS',
      options: [
        { label: 'LRS (Locally Redundant)', value: 'LRS' },
        { label: 'GRS (Geo-Redundant)', value: 'GRS' },
        { label: 'RAGRS (Read-Access Geo-Redundant)', value: 'RAGRS' },
        { label: 'ZRS (Zone-Redundant)', value: 'ZRS' },
        { label: 'GZRS (Geo-Zone-Redundant)', value: 'GZRS' },
        { label: 'RAGZRS (Read-Access Geo-Zone-Redundant)', value: 'RAGZRS' },
      ],
    },
    {
      key: 'account_kind',
      label: 'Account Kind',
      type: 'select',
      required: false,
      group: 'Advanced',
      order: 4,
      defaultValue: 'StorageV2',
      options: [
        { label: 'StorageV2 (General Purpose v2)', value: 'StorageV2' },
        { label: 'BlobStorage', value: 'BlobStorage' },
        { label: 'Storage (General Purpose v1)', value: 'Storage' },
      ],
    },
    {
      key: 'access_tier',
      label: 'Access Tier',
      type: 'select',
      required: false,
      group: 'Advanced',
      order: 5,
      defaultValue: 'Hot',
      options: [
        { label: 'Hot', value: 'Hot' },
        { label: 'Cool', value: 'Cool' },
      ],
    },
    {
      key: 'min_tls_version',
      label: 'Minimum TLS Version',
      type: 'select',
      required: false,
      group: 'Security',
      order: 6,
      defaultValue: 'TLS1_2',
      options: [
        { label: 'TLS 1.2', value: 'TLS1_2' },
        { label: 'TLS 1.1', value: 'TLS1_1' },
        { label: 'TLS 1.0', value: 'TLS1_0' },
      ],
    },
    {
      key: 'https_traffic_only_enabled',
      label: 'HTTPS Only',
      type: 'boolean',
      required: false,
      group: 'Security',
      order: 7,
      defaultValue: true,
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    {
      key: 'primary_connection_string',
      label: 'Connection String',
      terraformAttribute: 'primary_connection_string',
      sensitive: true,
    },
    {
      key: 'primary_access_key',
      label: 'Access Key',
      terraformAttribute: 'primary_access_key',
      sensitive: true,
    },
    { key: 'primary_blob_endpoint', label: 'Blob Endpoint', terraformAttribute: 'primary_blob_endpoint' },
  ],
};
