import type { ResourceSchema } from '@terrastudio/types';

export const vmScaleSetSchema: ResourceSchema = {
  typeId: 'azurerm/compute/virtual_machine_scale_set',
  provider: 'azurerm',
  displayName: 'VM Scale Set',
  category: 'compute',
  description: 'Azure Virtual Machine Scale Set for auto-scaling VM groups',
  terraformType: 'azurerm_linux_virtual_machine_scale_set',
  supportsTags: true,
  requiresResourceGroup: true,
  cafAbbreviation: 'vmss',
  namingConstraints: { maxLength: 64 },
  canBeChildOf: ['azurerm/networking/subnet'],
  parentReference: { propertyKey: 'subnet_id' },
  properties: [
    { key: 'name', label: 'Name', type: 'string', required: true, placeholder: 'vmss-web-dev', group: 'General', order: 1,
      validation: { minLength: 1, maxLength: 64, pattern: '^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]$', patternMessage: 'Alphanumerics and hyphens' } },
    { key: 'os_type', label: 'OS Type', type: 'select', required: true, group: 'General', order: 2, defaultValue: 'linux',
      options: [{ label: 'Linux', value: 'linux' }, { label: 'Windows', value: 'windows' }] },
    { key: 'sku', label: 'VM Size', type: 'select', required: true, group: 'General', order: 3, defaultValue: 'Standard_B2s',
      options: [
        { label: 'B1s (1 vCPU, 1 GB)', value: 'Standard_B1s' },
        { label: 'B2s (2 vCPU, 4 GB)', value: 'Standard_B2s' },
        { label: 'B2ms (2 vCPU, 8 GB)', value: 'Standard_B2ms' },
        { label: 'D2s v3 (2 vCPU, 8 GB)', value: 'Standard_D2s_v3' },
        { label: 'D4s v3 (4 vCPU, 16 GB)', value: 'Standard_D4s_v3' },
        { label: 'D8s v3 (8 vCPU, 32 GB)', value: 'Standard_D8s_v3' },
      ] },
    { key: 'instances', label: 'Instance Count', type: 'number', required: true, group: 'Scaling', order: 4, defaultValue: 2,
      validation: { min: 0, max: 1000 } },
    { key: 'admin_username', label: 'Admin Username', type: 'string', required: true, group: 'Authentication', order: 5, defaultValue: 'azureuser' },
    { key: 'admin_password', label: 'Admin Password', type: 'string', required: false, sensitive: true, group: 'Authentication', order: 6,
      description: 'Required for Windows VMSS',
      visibleWhen: { field: 'os_type', operator: 'eq', value: 'windows' } },
    { key: 'image_publisher', label: 'Image Publisher', type: 'string', required: true, group: 'OS Image', order: 7, defaultValue: 'Canonical' },
    { key: 'image_offer', label: 'Image Offer', type: 'string', required: true, group: 'OS Image', order: 8, defaultValue: '0001-com-ubuntu-server-jammy' },
    { key: 'image_sku', label: 'Image SKU', type: 'string', required: true, group: 'OS Image', order: 9, defaultValue: '22_04-lts' },
    { key: 'os_disk_size_gb', label: 'OS Disk Size (GB)', type: 'number', required: false, group: 'Storage', order: 10, defaultValue: 30 },
    { key: 'os_disk_type', label: 'OS Disk Type', type: 'select', required: true, group: 'Storage', order: 11, defaultValue: 'Standard_LRS',
      options: [
        { label: 'Standard HDD', value: 'Standard_LRS' },
        { label: 'Standard SSD', value: 'StandardSSD_LRS' },
        { label: 'Premium SSD', value: 'Premium_LRS' },
      ] },
    { key: 'upgrade_mode', label: 'Upgrade Mode', type: 'select', required: false, group: 'Scaling', order: 12, defaultValue: 'Manual',
      options: [
        { label: 'Automatic', value: 'Automatic' },
        { label: 'Manual', value: 'Manual' },
        { label: 'Rolling', value: 'Rolling' },
      ] },
    { key: 'single_placement_group', label: 'Single Placement Group', type: 'boolean', required: false, group: 'Scaling', order: 13, defaultValue: true },
    { key: 'overprovision', label: 'Overprovision', type: 'boolean', required: false, group: 'Scaling', order: 14, defaultValue: true },
    { key: 'zones', label: 'Availability Zones', type: 'multiselect', required: false, group: 'Availability', order: 15,
      options: [{ label: 'Zone 1', value: '1' }, { label: 'Zone 2', value: '2' }, { label: 'Zone 3', value: '3' }] },
  ],
  handles: [
    { id: 'lb-backend-in', type: 'target', position: 'top', label: 'Load Balancer' },
  ],
  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'unique_id', label: 'Unique ID', terraformAttribute: 'unique_id' },
  ],
};
