import type { ResourceSchema } from '@terrastudio/types';

export const vpnGatewaySchema: ResourceSchema = {
  typeId: 'azurerm/networking/virtual_network_gateway',
  provider: 'azurerm',
  displayName: 'VPN Gateway',
  category: 'networking',
  description: 'Azure VPN Gateway — sends encrypted traffic between an Azure virtual network and an on-premises location or other VNets',
  terraformType: 'azurerm_virtual_network_gateway',
  supportsTags: true,
  requiresResourceGroup: true,
  cafAbbreviation: 'vpng',
  namingConstraints: { maxLength: 80 },

  canBeChildOf: [
    'azurerm/core/resource_group',
  ],

  properties: [
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      required: true,
      placeholder: 'vpng-myapp-dev',
      group: 'General',
      order: 1,
      validation: {
        minLength: 1,
        maxLength: 80,
        pattern: '^[a-zA-Z0-9][a-zA-Z0-9_.-]*[a-zA-Z0-9_]$',
        patternMessage: 'Must start with alphanumeric, end with alphanumeric or underscore',
      },
    },
    {
      key: 'type',
      label: 'Gateway Type',
      type: 'select',
      required: true,
      group: 'General',
      order: 2,
      defaultValue: 'Vpn',
      options: [
        { label: 'VPN', value: 'Vpn' },
        { label: 'ExpressRoute', value: 'ExpressRoute' },
      ],
    },
    {
      key: 'vpn_type',
      label: 'VPN Type',
      type: 'select',
      required: false,
      group: 'General',
      order: 3,
      defaultValue: 'RouteBased',
      options: [
        { label: 'Route-based', value: 'RouteBased' },
        { label: 'Policy-based', value: 'PolicyBased' },
      ],
      visibleWhen: { field: 'type', operator: 'eq', value: 'Vpn' },
    },
    {
      key: 'sku',
      label: 'SKU',
      type: 'select',
      required: true,
      group: 'General',
      order: 4,
      defaultValue: 'VpnGw1',
      options: [
        { label: 'Basic', value: 'Basic' },
        { label: 'VpnGw1', value: 'VpnGw1' },
        { label: 'VpnGw2', value: 'VpnGw2' },
        { label: 'VpnGw3', value: 'VpnGw3' },
        { label: 'VpnGw4', value: 'VpnGw4' },
        { label: 'VpnGw5', value: 'VpnGw5' },
        { label: 'VpnGw1AZ', value: 'VpnGw1AZ' },
        { label: 'VpnGw2AZ', value: 'VpnGw2AZ' },
        { label: 'VpnGw3AZ', value: 'VpnGw3AZ' },
        { label: 'VpnGw4AZ', value: 'VpnGw4AZ' },
        { label: 'VpnGw5AZ', value: 'VpnGw5AZ' },
      ],
    },
    {
      key: 'generation',
      label: 'Generation',
      type: 'select',
      required: false,
      group: 'General',
      order: 5,
      defaultValue: 'Generation1',
      options: [
        { label: 'Generation 1', value: 'Generation1' },
        { label: 'Generation 2', value: 'Generation2' },
        { label: 'None', value: 'None' },
      ],
    },
    {
      key: 'active_active',
      label: 'Active-Active',
      type: 'boolean',
      required: false,
      group: 'High Availability',
      order: 10,
      defaultValue: false,
      description: 'Enable active-active mode (requires two public IPs and VpnGw1+ SKU)',
    },
    {
      key: 'enable_bgp',
      label: 'Enable BGP',
      type: 'boolean',
      required: false,
      group: 'Routing',
      order: 20,
      defaultValue: false,
      description: 'Enable Border Gateway Protocol (BGP)',
    },
    {
      key: 'bgp_asn',
      label: 'BGP ASN',
      type: 'number',
      required: false,
      group: 'Routing',
      order: 21,
      defaultValue: 65515,
      description: 'Autonomous System Number for BGP peering (default: 65515)',
      validation: { min: 1, max: 4294967295 },
      visibleWhen: { field: 'enable_bgp', operator: 'eq', value: true },
    },
    {
      key: 'subnet_id',
      label: 'Gateway Subnet',
      type: 'reference',
      required: false,
      group: 'Network',
      order: 30,
      referenceTargetTypes: ['azurerm/networking/subnet'],
      description: 'The subnet must be named "GatewaySubnet"',
    },
    {
      key: 'pip_id',
      label: 'Public IP',
      type: 'reference',
      required: false,
      group: 'Network',
      order: 31,
      referenceTargetTypes: ['azurerm/networking/public_ip'],
      description: 'Primary public IP address (Standard SKU, Static allocation)',
    },
    {
      key: 'pip2_id',
      label: 'Second Public IP (Active-Active)',
      type: 'reference',
      required: false,
      group: 'Network',
      order: 32,
      referenceTargetTypes: ['azurerm/networking/public_ip'],
      description: 'Second public IP for active-active configuration',
      visibleWhen: { field: 'active_active', operator: 'eq', value: true },
    },
    {
      key: 'vpn_client_enabled',
      label: 'Point-to-Site VPN',
      type: 'boolean',
      required: false,
      group: 'VPN Client',
      order: 40,
      defaultValue: false,
    },
    {
      key: 'vpn_client_address_pool',
      label: 'Client Address Pool',
      type: 'array',
      required: false,
      group: 'VPN Client',
      order: 41,
      visibleWhen: { field: 'vpn_client_enabled', operator: 'truthy' as const },
      itemSchema: {
        key: 'cidr',
        label: 'CIDR',
        type: 'cidr',
        required: true,
      },
    },
    {
      key: 'vpn_client_protocols',
      label: 'VPN Protocols',
      type: 'multiselect',
      required: false,
      group: 'VPN Client',
      order: 42,
      options: [
        { label: 'SSTP', value: 'SSTP' },
        { label: 'IKEv2', value: 'IkeV2' },
        { label: 'OpenVPN', value: 'OpenVPN' },
      ],
      visibleWhen: { field: 'vpn_client_enabled', operator: 'truthy' as const },
    },
  ],

  handles: [],

  outputs: [
    { key: 'id', label: 'Resource ID', terraformAttribute: 'id' },
    { key: 'bgp_peering_address', label: 'BGP Peering Address', terraformAttribute: 'bgp_settings.0.peering_address' },
  ],

  costEstimation: {
    serviceName: 'VPN Gateway',
    skuProperty: 'sku',
    usageInputs: [
      {
        key: '_cost_s2s_tunnels',
        label: 'S2S VPN Tunnels',
        unit: 'tunnels',
        defaultValue: 1,
        min: 0,
        max: 100,
        description: 'Number of site-to-site VPN tunnels',
      },
      {
        key: '_cost_data_transfer_gb',
        label: 'Data Transfer',
        unit: 'GB/mo',
        defaultValue: 100,
        min: 0,
        max: 1000000,
        description: 'Outbound data transfer per month',
      },
    ],
  },
};
